package database

type StatementID string

type StatementDefinition struct {
	ID    StatementID
	SQL   string
	Async bool
}

var LoginStatements = []StatementDefinition{
	{ID: "LOGIN_SEL_REALMLIST", SQL: "SELECT id, name, address, localAddress, localSubnetMask, port, icon, flag, timezone, allowedSecurityLevel, population, gamebuild FROM realmlist WHERE flag <> 3 ORDER BY name", Async: false},
	{ID: "LOGIN_DEL_EXPIRED_IP_BANS", SQL: "DELETE FROM ip_banned WHERE unbandate<>bandate AND unbandate<=UNIX_TIMESTAMP()", Async: true},
	{ID: "LOGIN_UPD_EXPIRED_ACCOUNT_BANS", SQL: "UPDATE account_banned SET active = 0 WHERE active = 1 AND unbandate<>bandate AND unbandate<=UNIX_TIMESTAMP()", Async: true},
	{ID: "LOGIN_SEL_IP_INFO", SQL: "SELECT unbandate > UNIX_TIMESTAMP() OR unbandate = bandate AS banned, NULL as country FROM ip_banned WHERE ip = ?", Async: true},
	{ID: "LOGIN_INS_IP_AUTO_BANNED", SQL: "INSERT INTO ip_banned (ip, bandate, unbandate, bannedby, banreason) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, 'Trinity Auth', 'Failed login autoban')", Async: true},
	{ID: "LOGIN_SEL_IP_BANNED_ALL", SQL: "SELECT ip, bandate, unbandate, bannedby, banreason FROM ip_banned WHERE (bandate = unbandate OR unbandate > UNIX_TIMESTAMP()) ORDER BY unbandate", Async: false},
	{ID: "LOGIN_SEL_IP_BANNED_BY_IP", SQL: "SELECT ip, bandate, unbandate, bannedby, banreason FROM ip_banned WHERE (bandate = unbandate OR unbandate > UNIX_TIMESTAMP()) AND ip LIKE CONCAT('%%', ?, '%%') ORDER BY unbandate", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_BANNED_ALL", SQL: "SELECT account.id, username FROM account, account_banned WHERE account.id = account_banned.id AND active = 1 GROUP BY account.id", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_BANNED_BY_FILTER", SQL: "SELECT account.id, username FROM account, account_banned WHERE account.id = account_banned.id AND active = 1 AND username LIKE CONCAT('%%', ?, '%%') GROUP BY account.id", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_BANNED_BY_USERNAME", SQL: "SELECT account.id, username FROM account, account_banned WHERE account.id = account_banned.id AND active = 1 AND username = ? GROUP BY account.id", Async: false},
	{ID: "LOGIN_INS_ACCOUNT_AUTO_BANNED", SQL: "INSERT INTO account_banned (id, bandate, unbandate, bannedby, banreason, active) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, 'Trinity Auth', 'Failed login autoban', 1)", Async: true},
	{ID: "LOGIN_DEL_ACCOUNT_BANNED", SQL: "DELETE FROM account_banned WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_LOGON", SQL: "UPDATE account SET salt = ?, verifier = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_LOGONPROOF", SQL: "UPDATE account SET session_key_auth = ?, last_ip = ?, last_login = NOW(), locale = ?, failed_logins = 0, os = ? WHERE username = ?", Async: false},
	{ID: "LOGIN_SEL_LOGONCHALLENGE", SQL: "SELECT a.id, a.username, a.locked, a.lock_country, a.last_ip, a.failed_logins, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.SecurityLevel, a.totp_secret, a.salt, a.verifier FROM account a LEFT JOIN account_access aa ON a.id = aa.AccountID LEFT JOIN account_banned ab ON ab.id = a.id AND ab.active = 1 WHERE a.username = ?", Async: true},
	{ID: "LOGIN_SEL_RECONNECTCHALLENGE", SQL: "SELECT a.id, UPPER(a.username), a.locked, a.lock_country, a.last_ip, a.failed_logins, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.SecurityLevel, a.session_key_auth FROM account a LEFT JOIN account_access aa ON a.id = aa.AccountID LEFT JOIN account_banned ab ON ab.id = a.id AND ab.active = 1 WHERE a.username = ? AND a.session_key_auth IS NOT NULL", Async: true},
	{ID: "LOGIN_UPD_FAILEDLOGINS", SQL: "UPDATE account SET failed_logins = failed_logins + 1 WHERE username = ?", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_ID_BY_NAME", SQL: "SELECT id FROM account WHERE username = ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_LIST_BY_NAME", SQL: "SELECT id, username FROM account WHERE username = ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_INFO_BY_NAME", SQL: "SELECT a.id, a.session_key_auth, a.last_ip, a.locked, a.lock_country, a.expansion, a.mutetime, a.locale, a.recruiter, a.os, aa.SecurityLevel, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, r.id FROM account a LEFT JOIN account_access aa ON a.id = aa.AccountID AND aa.RealmID IN (-1, ?) LEFT JOIN account_banned ab ON a.id = ab.id AND ab.active = 1 LEFT JOIN account r ON a.id = r.recruiter WHERE a.username = ? AND a.session_key_auth IS NOT NULL ORDER BY aa.RealmID DESC LIMIT 1", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_LIST_BY_EMAIL", SQL: "SELECT id, username FROM account WHERE email = ?", Async: false},
	{ID: "LOGIN_SEL_REALM_CHARACTER_COUNTS", SQL: "SELECT realmid, numchars FROM realmcharacters WHERE  acctid = ?", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_BY_IP", SQL: "SELECT id, username FROM account WHERE last_ip = ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_BY_ID", SQL: "SELECT 1 FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_INS_IP_BANNED", SQL: "INSERT INTO ip_banned (ip, bandate, unbandate, bannedby, banreason) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, ?, ?)", Async: true},
	{ID: "LOGIN_DEL_IP_NOT_BANNED", SQL: "DELETE FROM ip_banned WHERE ip = ?", Async: true},
	{ID: "LOGIN_INS_ACCOUNT_BANNED", SQL: "INSERT INTO account_banned (id, bandate, unbandate, bannedby, banreason, active) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, ?, ?, 1)", Async: true},
	{ID: "LOGIN_UPD_ACCOUNT_NOT_BANNED", SQL: "UPDATE account_banned SET active = 0 WHERE id = ? AND active != 0", Async: true},
	{ID: "LOGIN_DEL_REALM_CHARACTERS", SQL: "DELETE FROM realmcharacters WHERE acctid = ?", Async: true},
	{ID: "LOGIN_REP_REALM_CHARACTERS", SQL: "REPLACE INTO realmcharacters (numchars, acctid, realmid) VALUES (?, ?, ?)", Async: true},
	{ID: "LOGIN_SEL_SUM_REALM_CHARACTERS", SQL: "SELECT SUM(numchars) FROM realmcharacters WHERE acctid = ?", Async: true},
	{ID: "LOGIN_INS_ACCOUNT", SQL: "INSERT INTO account(username, salt, verifier, reg_mail, email, joindate) VALUES(?, ?, ?, ?, ?, NOW())", Async: false},
	{ID: "LOGIN_INS_REALM_CHARACTERS_INIT", SQL: "INSERT INTO realmcharacters (realmid, acctid, numchars) SELECT realmlist.id, account.id, 0 FROM realmlist, account LEFT JOIN realmcharacters ON acctid = account.id WHERE acctid IS NULL", Async: true},
	{ID: "LOGIN_UPD_EXPANSION", SQL: "UPDATE account SET expansion = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_ACCOUNT_LOCK", SQL: "UPDATE account SET locked = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_ACCOUNT_LOCK_COUNTRY", SQL: "UPDATE account SET lock_country = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_INS_LOG", SQL: "INSERT INTO logs (time, realm, type, level, string) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "LOGIN_UPD_USERNAME", SQL: "UPDATE account SET username = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_EMAIL", SQL: "UPDATE account SET email = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_REG_EMAIL", SQL: "UPDATE account SET reg_mail = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_MUTE_TIME", SQL: "UPDATE account SET mutetime = ? , mutereason = ? , muteby = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_MUTE_TIME_LOGIN", SQL: "UPDATE account SET mutetime = ? WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_LAST_IP", SQL: "UPDATE account SET last_ip = ? WHERE username = ?", Async: true},
	{ID: "LOGIN_UPD_LAST_ATTEMPT_IP", SQL: "UPDATE account SET last_attempt_ip = ? WHERE username = ?", Async: true},
	{ID: "LOGIN_UPD_ACCOUNT_ONLINE", SQL: "UPDATE account SET online = 1 WHERE id = ?", Async: true},
	{ID: "LOGIN_UPD_UPTIME_PLAYERS", SQL: "UPDATE uptime SET uptime = ?, maxplayers = ? WHERE realmid = ? AND starttime = ?", Async: true},
	{ID: "LOGIN_DEL_OLD_LOGS", SQL: "DELETE FROM logs WHERE (time + ?) < ? AND realm = ?", Async: true},
	{ID: "LOGIN_DEL_ACCOUNT_ACCESS", SQL: "DELETE FROM account_access WHERE AccountID = ?", Async: true},
	{ID: "LOGIN_DEL_ACCOUNT_ACCESS_BY_REALM", SQL: "DELETE FROM account_access WHERE AccountID = ? AND (RealmID = ? OR RealmID = -1)", Async: true},
	{ID: "LOGIN_INS_ACCOUNT_ACCESS", SQL: "INSERT INTO account_access (AccountID, SecurityLevel, RealmID) VALUES (?, ?, ?)", Async: true},
	{ID: "LOGIN_GET_ACCOUNT_ID_BY_USERNAME", SQL: "SELECT id FROM account WHERE username = ?", Async: false},
	{ID: "LOGIN_GET_GMLEVEL_BY_REALMID", SQL: "SELECT SecurityLevel FROM account_access WHERE AccountID = ? AND (RealmID = ? OR RealmID = -1) ORDER BY RealmID DESC", Async: false},
	{ID: "LOGIN_GET_USERNAME_BY_ID", SQL: "SELECT username FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_SEL_CHECK_PASSWORD", SQL: "SELECT salt, verifier FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_SEL_CHECK_PASSWORD_BY_NAME", SQL: "SELECT salt, verifier FROM account WHERE username = ?", Async: false},
	{ID: "LOGIN_SEL_PINFO", SQL: "SELECT a.username, aa.SecurityLevel, a.email, a.reg_mail, a.last_ip, DATE_FORMAT(a.last_login, '%Y-%m-%d %T'), a.mutetime, a.mutereason, a.muteby, a.failed_logins, a.locked, a.OS FROM account a LEFT JOIN account_access aa ON (a.id = aa.AccountID AND (aa.RealmID = ? OR aa.RealmID = -1)) WHERE a.id = ?", Async: false},
	{ID: "LOGIN_SEL_PINFO_BANS", SQL: "SELECT unbandate, bandate = unbandate, bannedby, banreason FROM account_banned WHERE id = ? AND active ORDER BY bandate ASC LIMIT 1", Async: false},
	{ID: "LOGIN_SEL_GM_ACCOUNTS", SQL: "SELECT a.username, aa.SecurityLevel FROM account a, account_access aa WHERE a.id = aa.AccountID AND aa.SecurityLevel >= ? AND (aa.RealmID = -1 OR aa.RealmID = ?)", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_INFO", SQL: "SELECT a.username, a.last_ip, aa.SecurityLevel, a.expansion FROM account a LEFT JOIN account_access aa ON a.id = aa.AccountID WHERE a.id = ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_ACCESS_SECLEVEL_TEST", SQL: "SELECT 1 FROM account_access WHERE AccountID = ? AND SecurityLevel > ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_ACCESS", SQL: "SELECT a.id, aa.SecurityLevel, aa.RealmID FROM account a LEFT JOIN account_access aa ON a.id = aa.AccountID WHERE a.username = ?", Async: false},
	{ID: "LOGIN_SEL_ACCOUNT_WHOIS", SQL: "SELECT username, email, last_ip FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_SEL_LAST_ATTEMPT_IP", SQL: "SELECT last_attempt_ip FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_SEL_LAST_IP", SQL: "SELECT last_ip FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_SEL_REALMLIST_SECURITY_LEVEL", SQL: "SELECT allowedSecurityLevel from realmlist WHERE id = ?", Async: false},
	{ID: "LOGIN_DEL_ACCOUNT", SQL: "DELETE FROM account WHERE id = ?", Async: true},
	{ID: "LOGIN_SEL_AUTOBROADCAST", SQL: "SELECT id, weight, text FROM autobroadcast WHERE realmid = ? OR realmid = -1", Async: false},
	{ID: "LOGIN_GET_EMAIL_BY_ID", SQL: "SELECT email FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_INS_ALDL_IP_LOGGING", SQL: "INSERT INTO logs_ip_actions (account_id, character_guid, realm_id, type, ip, systemnote, unixtime, time) VALUES (?, ?, ?, ?, (SELECT last_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())", Async: true},
	{ID: "LOGIN_INS_FACL_IP_LOGGING", SQL: "INSERT INTO logs_ip_actions (account_id, character_guid, realm_id, type, ip, systemnote, unixtime, time) VALUES (?, ?, ?, ?, (SELECT last_attempt_ip FROM account WHERE id = ?), ?, unix_timestamp(NOW()), NOW())", Async: true},
	{ID: "LOGIN_INS_CHAR_IP_LOGGING", SQL: "INSERT INTO logs_ip_actions (account_id, character_guid, realm_id, type, ip, systemnote, unixtime, time) VALUES (?, ?, ?, ?, ?, ?, unix_timestamp(NOW()), NOW())", Async: true},
	{ID: "LOGIN_INS_FALP_IP_LOGGING", SQL: "INSERT INTO logs_ip_actions (account_id, character_guid, realm_id, type, ip, systemnote, unixtime, time) VALUES (?, 0, 0, 1, ?, ?, unix_timestamp(NOW()), NOW())", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_ACCESS_BY_ID", SQL: "SELECT SecurityLevel, RealmID FROM account_access WHERE AccountID = ? and (RealmID = ? OR RealmID = -1) ORDER BY SecurityLevel desc", Async: false},
	{ID: "LOGIN_SEL_RBAC_ACCOUNT_PERMISSIONS", SQL: "SELECT permissionId, granted FROM rbac_account_permissions WHERE accountId = ? AND (realmId = ? OR realmId = -1) ORDER BY permissionId, realmId", Async: false},
	{ID: "LOGIN_INS_RBAC_ACCOUNT_PERMISSION", SQL: "INSERT INTO rbac_account_permissions (accountId, permissionId, granted, realmId) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE granted = VALUES(granted)", Async: true},
	{ID: "LOGIN_DEL_RBAC_ACCOUNT_PERMISSION", SQL: "DELETE FROM rbac_account_permissions WHERE accountId = ? AND permissionId = ? AND (realmId = ? OR realmId = -1)", Async: true},
	{ID: "LOGIN_INS_ACCOUNT_MUTE", SQL: "INSERT INTO account_muted VALUES (?, UNIX_TIMESTAMP(), ?, ?, ?)", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_MUTE_INFO", SQL: "SELECT mutedate, mutetime, mutereason, mutedby FROM account_muted WHERE guid = ? ORDER BY mutedate ASC", Async: false},
	{ID: "LOGIN_DEL_ACCOUNT_MUTED", SQL: "DELETE FROM account_muted WHERE guid = ?", Async: true},
	{ID: "LOGIN_SEL_SECRET_DIGEST", SQL: "SELECT digest FROM secret_digest WHERE id = ?", Async: false},
	{ID: "LOGIN_INS_SECRET_DIGEST", SQL: "INSERT INTO secret_digest (id, digest) VALUES (?,?)", Async: true},
	{ID: "LOGIN_DEL_SECRET_DIGEST", SQL: "DELETE FROM secret_digest WHERE id = ?", Async: true},
	{ID: "LOGIN_SEL_ACCOUNT_TOTP_SECRET", SQL: "SELECT totp_secret FROM account WHERE id = ?", Async: false},
	{ID: "LOGIN_UPD_ACCOUNT_TOTP_SECRET", SQL: "UPDATE account SET totp_secret = ? WHERE id = ?", Async: true},
}

var CharacterStatements = []StatementDefinition{
	{ID: "CHAR_DEL_POOL_QUEST_SAVE", SQL: "DELETE FROM pool_quest_save WHERE pool_id = ?", Async: true},
	{ID: "CHAR_INS_POOL_QUEST_SAVE", SQL: "INSERT INTO pool_quest_save (pool_id, quest_id) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_NONEXISTENT_GUILD_BANK_ITEM", SQL: "DELETE FROM guild_bank_item WHERE guildid = ? AND TabId = ? AND SlotId = ?", Async: true},
	{ID: "CHAR_DEL_EXPIRED_BANS", SQL: "UPDATE character_banned SET active = 0 WHERE unbandate <= UNIX_TIMESTAMP() AND unbandate <> bandate", Async: true},
	{ID: "CHAR_SEL_CHECK_NAME", SQL: "SELECT 1 FROM characters WHERE name = ?", Async: false},
	{ID: "CHAR_SEL_CHECK_GUID", SQL: "SELECT 1 FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_SUM_CHARS", SQL: "SELECT COUNT(guid) FROM characters WHERE account = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_CREATE_INFO", SQL: "SELECT level, race, class FROM characters WHERE account = ? LIMIT 0, ?", Async: true},
	{ID: "CHAR_INS_CHARACTER_BAN", SQL: "INSERT INTO character_banned (guid, bandate, unbandate, bannedby, banreason, active) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, ?, ?, 1)", Async: true},
	{ID: "CHAR_UPD_CHARACTER_BAN", SQL: "UPDATE character_banned SET active = 0 WHERE guid = ? AND active != 0", Async: true},
	{ID: "CHAR_DEL_CHARACTER_BAN", SQL: "DELETE cb FROM character_banned cb INNER JOIN characters c ON c.guid = cb.guid WHERE c.account = ?", Async: true},
	{ID: "CHAR_SEL_BANINFO", SQL: "SELECT bandate, unbandate-bandate, active, unbandate, banreason, bannedby FROM character_banned WHERE guid = ? ORDER BY bandate ASC", Async: false},
	{ID: "CHAR_SEL_GUID_BY_NAME_FILTER", SQL: "SELECT guid, name FROM characters WHERE name LIKE CONCAT('%%', ?, '%%')", Async: false},
	{ID: "CHAR_SEL_BANINFO_LIST", SQL: "SELECT bandate, unbandate, bannedby, banreason FROM character_banned WHERE guid = ? ORDER BY unbandate", Async: false},
	{ID: "CHAR_SEL_BANNED_NAME", SQL: "SELECT characters.name FROM characters, character_banned WHERE character_banned.guid = ? AND character_banned.guid = characters.guid", Async: false},
	{ID: "CHAR_SEL_MAIL_LIST_COUNT", SQL: "SELECT COUNT(id) FROM mail WHERE receiver = ? ", Async: false},
	{ID: "CHAR_SEL_MAIL_LIST_INFO", SQL: "SELECT id, sender, (SELECT name FROM characters WHERE guid = sender) AS sendername, receiver, (SELECT name FROM characters WHERE guid = receiver) AS receivername, subject, deliver_time, expire_time, money, has_items FROM mail WHERE receiver = ? ", Async: false},
	{ID: "CHAR_SEL_MAIL_LIST_ITEMS", SQL: "SELECT itemEntry,count FROM item_instance WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_ENUM", SQL: "SELECT c.guid, c.name, c.race, c.class, c.gender, c.skin, c.face, c.hairStyle, c.hairColor, c.facialStyle, c.level, c.zone, c.map, c.position_x, c.position_y, c.position_z, gm.guildid, c.playerFlags, c.at_login, cp.entry, cp.modelid, cp.level, c.equipmentCache, cb.guid FROM characters AS c LEFT JOIN character_pet AS cp ON c.guid = cp.owner AND cp.slot = ? LEFT JOIN guild_member AS gm ON c.guid = gm.guid LEFT JOIN character_banned AS cb ON c.guid = cb.guid AND cb.active = 1 WHERE c.account = ? AND c.deleteInfos_Name IS NULL ORDER BY c.guid", Async: true},
	{ID: "CHAR_SEL_ENUM_DECLINED_NAME", SQL: "SELECT c.guid, c.name, c.race, c.class, c.gender, c.skin, c.face, c.hairStyle, c.hairColor, c.facialStyle, c.level, c.zone, c.map, c.position_x, c.position_y, c.position_z, gm.guildid, c.playerFlags, c.at_login, cp.entry, cp.modelid, cp.level, c.equipmentCache, cb.guid, cd.genitive FROM characters AS c LEFT JOIN character_pet AS cp ON c.guid = cp.owner AND cp.slot = ? LEFT JOIN character_declinedname AS cd ON c.guid = cd.guid LEFT JOIN guild_member AS gm ON c.guid = gm.guid LEFT JOIN character_banned AS cb ON c.guid = cb.guid AND cb.active = 1 WHERE c.account = ?  AND c.deleteInfos_Name IS NULL ORDER BY c.guid", Async: true},
	{ID: "CHAR_SEL_FREE_NAME", SQL: "SELECT guid, name, at_login FROM characters WHERE guid = ? AND account = ? AND NOT EXISTS (SELECT NULL FROM characters WHERE name = ?)", Async: true},
	{ID: "CHAR_SEL_CHAR_ZONE", SQL: "SELECT zone FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_NAME_DATA", SQL: "SELECT race, class, gender, level, name FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_POSITION_XYZ", SQL: "SELECT map, position_x, position_y, position_z FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_POSITION", SQL: "SELECT position_x, position_y, position_z, orientation, map, taxi_path FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_DEL_BATTLEGROUND_RANDOM_ALL", SQL: "DELETE FROM character_battleground_random", Async: true},
	{ID: "CHAR_DEL_BATTLEGROUND_RANDOM", SQL: "DELETE FROM character_battleground_random WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_BATTLEGROUND_RANDOM", SQL: "INSERT INTO character_battleground_random (guid) VALUES (?)", Async: true},
	{ID: "CHAR_SEL_CHARACTER", SQL: "SELECT c.guid, account, name, race, class, gender, level, xp, money, skin, face, hairStyle, hairColor, facialStyle, bankSlots, restState, playerFlags, position_x, position_y, position_z, map, orientation, taximask, cinematic, totaltime, leveltime, rest_bonus, logout_time, is_logout_resting, resettalents_cost, resettalents_time, trans_x, trans_y, trans_z, trans_o, transguid, extra_flags, stable_slots, at_login, zone, online, death_expire_time, taxi_path, instance_mode_mask, arenaPoints, totalHonorPoints, todayHonorPoints, yesterdayHonorPoints, totalKills, todayKills, yesterdayKills, chosenTitle, knownCurrencies, watchedFaction, drunk, health, power1, power2, power3, power4, power5, power6, power7, instance_id, talentGroupsCount, activeTalentGroup, exploredZones, equipmentCache, ammoId, knownTitles, actionBars, grantableLevels, fishingSteps FROM characters c LEFT JOIN character_fishingsteps cfs ON c.guid = cfs.guid WHERE c.guid = ?", Async: true},
	{ID: "CHAR_SEL_GROUP_MEMBER", SQL: "SELECT guid FROM group_member WHERE memberGuid = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_INSTANCE", SQL: "SELECT id, permanent, map, difficulty, extendState, resettime FROM character_instance LEFT JOIN instance ON instance = id WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_AURAS", SQL: "SELECT casterGuid, itemGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience FROM character_aura WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_SPELL", SQL: "SELECT spell, active, disabled FROM character_spell WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUS", SQL: "SELECT quest, status, explored, timer, mobcount1, mobcount2, mobcount3, mobcount4, itemcount1, itemcount2, itemcount3, itemcount4, itemcount5, itemcount6, playercount FROM character_queststatus WHERE guid = ? AND status <> 0", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUS_DAILY", SQL: "SELECT quest, time FROM character_queststatus_daily WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUS_WEEKLY", SQL: "SELECT quest FROM character_queststatus_weekly WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUS_MONTHLY", SQL: "SELECT quest FROM character_queststatus_monthly WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUS_SEASONAL", SQL: "SELECT quest, event FROM character_queststatus_seasonal WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_QUESTSTATUS_DAILY", SQL: "DELETE FROM character_queststatus_daily WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_QUESTSTATUS_WEEKLY", SQL: "DELETE FROM character_queststatus_weekly WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_QUESTSTATUS_MONTHLY", SQL: "DELETE FROM character_queststatus_monthly WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_QUESTSTATUS_SEASONAL", SQL: "DELETE FROM character_queststatus_seasonal WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHARACTER_QUESTSTATUS_DAILY", SQL: "INSERT INTO character_queststatus_daily (guid, quest, time) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_INS_CHARACTER_QUESTSTATUS_WEEKLY", SQL: "INSERT INTO character_queststatus_weekly (guid, quest) VALUES (?, ?)", Async: true},
	{ID: "CHAR_INS_CHARACTER_QUESTSTATUS_MONTHLY", SQL: "INSERT INTO character_queststatus_monthly (guid, quest) VALUES (?, ?)", Async: true},
	{ID: "CHAR_INS_CHARACTER_QUESTSTATUS_SEASONAL", SQL: "INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_RESET_CHARACTER_QUESTSTATUS_DAILY", SQL: "DELETE FROM character_queststatus_daily", Async: true},
	{ID: "CHAR_DEL_RESET_CHARACTER_QUESTSTATUS_WEEKLY", SQL: "DELETE FROM character_queststatus_weekly", Async: true},
	{ID: "CHAR_DEL_RESET_CHARACTER_QUESTSTATUS_MONTHLY", SQL: "DELETE FROM character_queststatus_monthly", Async: true},
	{ID: "CHAR_DEL_RESET_CHARACTER_QUESTSTATUS_SEASONAL_BY_EVENT", SQL: "DELETE FROM character_queststatus_seasonal WHERE event = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_REPUTATION", SQL: "SELECT faction, standing, flags FROM character_reputation WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_INVENTORY", SQL: "SELECT creatorGuid, giftCreatorGuid, count, duration, charges, flags, enchantments, randomPropertyId, durability, playedTime, text, bag, slot, item, itemEntry FROM character_inventory ci JOIN item_instance ii ON ci.item = ii.guid WHERE ci.guid = ? ORDER BY bag, slot", Async: true},
	{ID: "CHAR_SEL_CHARACTER_ACTIONS", SQL: "SELECT a.button, a.action, a.type FROM character_action as a, characters as c WHERE a.guid = c.guid AND a.spec = c.activeTalentGroup AND a.guid = ? ORDER BY button", Async: true},
	{ID: "CHAR_SEL_MAIL_COUNT", SQL: "SELECT COUNT(*) FROM mail WHERE receiver = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_SOCIALLIST", SQL: "SELECT friend, flags, note FROM character_social JOIN characters ON characters.guid = character_social.friend WHERE character_social.guid = ? AND deleteinfos_name IS NULL LIMIT 255", Async: true},
	{ID: "CHAR_SEL_CHARACTER_HOMEBIND", SQL: "SELECT mapId, zoneId, posX, posY, posZ FROM character_homebind WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_SPELLCOOLDOWNS", SQL: "SELECT spell, item, time, categoryId, categoryEnd FROM character_spell_cooldown WHERE guid = ? AND time > UNIX_TIMESTAMP()", Async: true},
	{ID: "CHAR_SEL_CHARACTER_DECLINEDNAMES", SQL: "SELECT genitive, dative, accusative, instrumental, prepositional FROM character_declinedname WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_GUILD_MEMBER", SQL: "SELECT guildid, `rank` FROM guild_member WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_GUILD_MEMBER_EXTENDED", SQL: "SELECT g.guildid, g.name, gr.rname, gr.rid, gm.pnote, gm.offnote FROM guild g JOIN guild_member gm ON g.guildid = gm.guildid JOIN guild_rank gr ON g.guildid = gr.guildid AND gm.`rank` = gr.rid WHERE gm.guid = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_ACHIEVEMENTS", SQL: "SELECT achievement, date FROM character_achievement WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_CRITERIAPROGRESS", SQL: "SELECT criteria, counter, date FROM character_achievement_progress WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_EQUIPMENTSETS", SQL: "SELECT setguid, setindex, name, iconname, ignore_mask, item0, item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14, item15, item16, item17, item18 FROM character_equipmentsets WHERE guid = ? ORDER BY setindex", Async: true},
	{ID: "CHAR_SEL_CHARACTER_BGDATA", SQL: "SELECT instanceId, team, joinX, joinY, joinZ, joinO, joinMapId, taxiStart, taxiEnd, mountSpell FROM character_battleground_data WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_GLYPHS", SQL: "SELECT talentGroup, glyph1, glyph2, glyph3, glyph4, glyph5, glyph6 FROM character_glyphs WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_TALENTS", SQL: "SELECT spell, talentGroup FROM character_talent WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_SKILLS", SQL: "SELECT skill, value, max FROM character_skills WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_RANDOMBG", SQL: "SELECT guid FROM character_battleground_random WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_BANNED", SQL: "SELECT guid FROM character_banned WHERE guid = ? AND active = 1", Async: true},
	{ID: "CHAR_SEL_CHARACTER_QUESTSTATUSREW", SQL: "SELECT quest FROM character_queststatus_rewarded WHERE guid = ? AND active = 1", Async: true},
	{ID: "CHAR_SEL_ACCOUNT_INSTANCELOCKTIMES", SQL: "SELECT instanceId, releaseTime FROM account_instance_times WHERE accountId = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_ACTIONS_SPEC", SQL: "SELECT button, action, type FROM character_action WHERE guid = ? AND spec = ? ORDER BY button", Async: true},
	{ID: "CHAR_SEL_MAILITEMS", SQL: "SELECT creatorGuid, giftCreatorGuid, count, duration, charges, flags, enchantments, randomPropertyId, durability, playedTime, text, item_guid, itemEntry, ii.owner_guid, m.id FROM mail_items mi INNER JOIN mail m ON mi.mail_id = m.id LEFT JOIN item_instance ii ON mi.item_guid = ii.guid WHERE m.receiver = ?", Async: true},
	{ID: "CHAR_SEL_AUCTION_ITEMS", SQL: "SELECT creatorGuid, giftCreatorGuid, count, duration, charges, ii.flags, enchantments, randomPropertyId, durability, playedTime, text, itemguid, itemEntry FROM auctionhouse ah JOIN item_instance ii ON ah.itemguid = ii.guid", Async: false},
	{ID: "CHAR_SEL_AUCTIONS", SQL: "SELECT id, houseid, itemguid, itemEntry, count, itemowner, buyoutprice, time, buyguid, lastbid, startbid, deposit, ah.Flags FROM auctionhouse ah INNER JOIN item_instance ii ON ii.guid = ah.itemguid", Async: false},
	{ID: "CHAR_INS_AUCTION", SQL: "INSERT INTO auctionhouse (id, houseid, itemguid, itemowner, buyoutprice, time, buyguid, lastbid, startbid, deposit, Flags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_AUCTION", SQL: "DELETE FROM auctionhouse WHERE id = ?", Async: true},
	{ID: "CHAR_SEL_AUCTION_BIDDERS", SQL: "SELECT id, bidderguid FROM auctionbidders", Async: false},
	{ID: "CHAR_INS_AUCTION_BIDDERS", SQL: "INSERT IGNORE INTO auctionbidders (id, bidderguid) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_AUCTION_BIDDERS", SQL: "DELETE FROM auctionbidders WHERE id = ?", Async: true},
	{ID: "CHAR_UPD_AUCTION_BID", SQL: "UPDATE auctionhouse SET buyguid = ?, lastbid = ?, Flags = ? WHERE id = ?", Async: true},
	{ID: "CHAR_INS_MAIL", SQL: "INSERT INTO mail(id, messageType, stationery, mailTemplateId, sender, receiver, subject, body, has_items, expire_time, deliver_time, money, cod, checked) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_MAIL_BY_ID", SQL: "DELETE FROM mail WHERE id = ?", Async: true},
	{ID: "CHAR_INS_MAIL_ITEM", SQL: "INSERT INTO mail_items(mail_id, item_guid, receiver) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_MAIL_ITEM", SQL: "DELETE FROM mail_items WHERE item_guid = ?", Async: true},
	{ID: "CHAR_DEL_INVALID_MAIL_ITEM", SQL: "DELETE FROM mail_items WHERE item_guid = ?", Async: true},
	{ID: "CHAR_DEL_EMPTY_EXPIRED_MAIL", SQL: "DELETE FROM mail WHERE expire_time < ? AND has_items = 0 AND body = ''", Async: true},
	{ID: "CHAR_SEL_EXPIRED_MAIL", SQL: "SELECT id, messageType, sender, receiver, has_items, expire_time, cod, checked, mailTemplateId FROM mail WHERE expire_time < ?", Async: false},
	{ID: "CHAR_SEL_EXPIRED_MAIL_ITEMS", SQL: "SELECT item_guid, itemEntry, mail_id FROM mail_items mi INNER JOIN item_instance ii ON ii.guid = mi.item_guid LEFT JOIN mail mm ON mi.mail_id = mm.id WHERE mm.id IS NOT NULL AND mm.expire_time < ?", Async: false},
	{ID: "CHAR_UPD_MAIL_RETURNED", SQL: "UPDATE mail SET sender = ?, receiver = ?, expire_time = ?, deliver_time = ?, cod = 0, checked = ? WHERE id = ?", Async: true},
	{ID: "CHAR_UPD_MAIL_ITEM_RECEIVER", SQL: "UPDATE mail_items SET receiver = ? WHERE item_guid = ?", Async: true},
	{ID: "CHAR_UPD_ITEM_OWNER", SQL: "UPDATE item_instance SET owner_guid = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_ITEM_REFUNDS", SQL: "SELECT player_guid, paidMoney, paidExtendedCost FROM item_refund_instance WHERE item_guid = ? AND player_guid = ? LIMIT 1", Async: false},
	{ID: "CHAR_SEL_ITEM_BOP_TRADE", SQL: "SELECT allowedPlayers FROM item_soulbound_trade_data WHERE itemGuid = ? LIMIT 1", Async: false},
	{ID: "CHAR_DEL_ITEM_BOP_TRADE", SQL: "DELETE FROM item_soulbound_trade_data WHERE itemGuid = ? LIMIT 1", Async: true},
	{ID: "CHAR_INS_ITEM_BOP_TRADE", SQL: "INSERT INTO item_soulbound_trade_data VALUES (?, ?)", Async: true},
	{ID: "CHAR_REP_INVENTORY_ITEM", SQL: "REPLACE INTO character_inventory (guid, bag, slot, item) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_REP_ITEM_INSTANCE", SQL: "REPLACE INTO item_instance (itemEntry, owner_guid, creatorGuid, giftCreatorGuid, count, duration, charges, flags, enchantments, randomPropertyId, durability, playedTime, text, guid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_ITEM_INSTANCE", SQL: "UPDATE item_instance SET itemEntry = ?, owner_guid = ?, creatorGuid = ?, giftCreatorGuid = ?, count = ?, duration = ?, charges = ?, flags = ?, enchantments = ?, randomPropertyId = ?, durability = ?, playedTime = ?, text = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_ITEM_INSTANCE_ON_LOAD", SQL: "UPDATE item_instance SET duration = ?, flags = ?, durability = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_ITEM_INSTANCE", SQL: "DELETE FROM item_instance WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_ITEM_INSTANCE_BY_OWNER", SQL: "DELETE FROM item_instance WHERE owner_guid = ?", Async: true},
	{ID: "CHAR_UPD_GIFT_OWNER", SQL: "UPDATE character_gifts SET guid = ? WHERE item_guid = ?", Async: true},
	{ID: "CHAR_DEL_GIFT", SQL: "DELETE FROM character_gifts WHERE item_guid = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_GIFT_BY_ITEM", SQL: "SELECT entry, flags FROM character_gifts WHERE item_guid = ?", Async: true},
	{ID: "CHAR_SEL_ACCOUNT_BY_NAME", SQL: "SELECT account FROM characters WHERE name = ?", Async: false},
	{ID: "CHAR_UPD_ACCOUNT_BY_GUID", SQL: "UPDATE characters SET account = ? WHERE guid = ?", Async: false},
	{ID: "CHAR_DEL_ACCOUNT_INSTANCE_LOCK_TIMES", SQL: "DELETE FROM account_instance_times WHERE accountId = ?", Async: true},
	{ID: "CHAR_INS_ACCOUNT_INSTANCE_LOCK_TIMES", SQL: "INSERT INTO account_instance_times (accountId, instanceId, releaseTime) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_MATCH_MAKER_RATING", SQL: "SELECT matchMakerRating FROM character_arena_stats WHERE guid = ? AND slot = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_COUNT", SQL: "SELECT account, COUNT(guid) FROM characters WHERE account = ? GROUP BY account", Async: true},
	{ID: "CHAR_UPD_NAME_BY_GUID", SQL: "UPDATE characters SET name = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_DECLINED_NAME", SQL: "DELETE FROM character_declinedname WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_GUILD", SQL: "INSERT INTO guild (guildid, name, leaderguid, info, motd, createdate, EmblemStyle, EmblemColor, BorderStyle, BorderColor, BackgroundColor, BankMoney) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD", SQL: "DELETE FROM guild WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_NAME", SQL: "UPDATE guild SET name = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_MEMBER", SQL: "INSERT INTO guild_member (guildid, guid, `rank`, pnote, offnote) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_MEMBER", SQL: "DELETE FROM guild_member WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_MEMBERS", SQL: "DELETE FROM guild_member WHERE guildid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_RANK", SQL: "INSERT INTO guild_rank (guildid, rid, rname, rights, BankMoneyPerDay) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_RANKS", SQL: "DELETE FROM guild_rank WHERE guildid = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_LOWEST_RANK", SQL: "DELETE FROM guild_rank WHERE guildid = ? AND rid >= ?", Async: true},
	{ID: "CHAR_INS_GUILD_BANK_TAB", SQL: "INSERT INTO guild_bank_tab (guildid, TabId) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_TAB", SQL: "DELETE FROM guild_bank_tab WHERE guildid = ? AND TabId = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_TABS", SQL: "DELETE FROM guild_bank_tab WHERE guildid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_BANK_ITEM", SQL: "INSERT INTO guild_bank_item (guildid, TabId, SlotId, item_guid) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_ITEM", SQL: "DELETE FROM guild_bank_item WHERE guildid = ? AND TabId = ? AND SlotId = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_ITEMS", SQL: "DELETE FROM guild_bank_item WHERE guildid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_BANK_RIGHT", SQL: "INSERT INTO guild_bank_right (guildid, TabId, rid, gbright, SlotPerDay) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE gbright = VALUES(gbright), SlotPerDay = VALUES(SlotPerDay)", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_RIGHTS", SQL: "DELETE FROM guild_bank_right WHERE guildid = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_RIGHTS_FOR_RANK", SQL: "DELETE FROM guild_bank_right WHERE guildid = ? AND rid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_BANK_EVENTLOG", SQL: "INSERT INTO guild_bank_eventlog (guildid, LogGuid, TabId, EventType, PlayerGuid, ItemOrMoney, ItemStackCount, DestTabId, TimeStamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_EVENTLOG", SQL: "DELETE FROM guild_bank_eventlog WHERE guildid = ? AND LogGuid = ? AND TabId = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_EVENTLOGS", SQL: "DELETE FROM guild_bank_eventlog WHERE guildid = ?", Async: true},
	{ID: "CHAR_INS_GUILD_EVENTLOG", SQL: "INSERT INTO guild_eventlog (guildid, LogGuid, EventType, PlayerGuid1, PlayerGuid2, NewRank, TimeStamp) VALUES (?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GUILD_EVENTLOG", SQL: "DELETE FROM guild_eventlog WHERE guildid = ? AND LogGuid = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_EVENTLOGS", SQL: "DELETE FROM guild_eventlog WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_MEMBER_PNOTE", SQL: "UPDATE guild_member SET pnote = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_MEMBER_OFFNOTE", SQL: "UPDATE guild_member SET offnote = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_MEMBER_RANK", SQL: "UPDATE guild_member SET `rank` = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_MOTD", SQL: "UPDATE guild SET motd = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_INFO", SQL: "UPDATE guild SET info = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_LEADER", SQL: "UPDATE guild SET leaderguid = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_RANK_NAME", SQL: "UPDATE guild_rank SET rname = ? WHERE rid = ? AND guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_RANK_RIGHTS", SQL: "UPDATE guild_rank SET rights = ? WHERE rid = ? AND guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_EMBLEM_INFO", SQL: "UPDATE guild SET EmblemStyle = ?, EmblemColor = ?, BorderStyle = ?, BorderColor = ?, BackgroundColor = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_BANK_TAB_INFO", SQL: "UPDATE guild_bank_tab SET TabName = ?, TabIcon = ? WHERE guildid = ? AND TabId = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_BANK_MONEY", SQL: "UPDATE guild SET BankMoney = ? WHERE guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_BANK_EVENTLOG_TAB", SQL: "UPDATE guild_bank_eventlog SET TabId = ? WHERE guildid = ? AND TabId = ? AND LogGuid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_RANK_BANK_MONEY", SQL: "UPDATE guild_rank SET BankMoneyPerDay = ? WHERE rid = ? AND guildid = ?", Async: true},
	{ID: "CHAR_UPD_GUILD_BANK_TAB_TEXT", SQL: "UPDATE guild_bank_tab SET TabText = ? WHERE guildid = ? AND TabId = ?", Async: true},
	{ID: "CHAR_INS_GUILD_MEMBER_WITHDRAW", SQL: "INSERT INTO guild_member_withdraw (guid, tab0, tab1, tab2, tab3, tab4, tab5, money) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE tab0 = VALUES (tab0), tab1 = VALUES (tab1), tab2 = VALUES (tab2), tab3 = VALUES (tab3), tab4 = VALUES (tab4), tab5 = VALUES (tab5)", Async: true},
	{ID: "CHAR_DEL_GUILD_MEMBER_WITHDRAW", SQL: "TRUNCATE guild_member_withdraw", Async: true},
	{ID: "CHAR_SEL_CHAR_DATA_FOR_GUILD", SQL: "SELECT name, level, class, gender, zone, account FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_UPD_CHANNEL", SQL: "INSERT INTO channels (name, team, announce, ownership, password, bannedList, lastUsed) VALUES (?, ?, ?, ?, ?, ?, UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE announce=VALUES(announce), ownership=VALUES(ownership), password=VALUES(password), bannedList=VALUES(bannedList), lastUsed=VALUES(lastUsed)", Async: true},
	{ID: "CHAR_UPD_CHANNEL_USAGE", SQL: "UPDATE channels SET lastUsed = UNIX_TIMESTAMP() WHERE name = ? AND team = ?", Async: true},
	{ID: "CHAR_UPD_CHANNEL_OWNERSHIP", SQL: "UPDATE channels SET ownership = ? WHERE name LIKE ?", Async: true},
	{ID: "CHAR_DEL_CHANNEL", SQL: "DELETE FROM channels WHERE name = ? AND team = ?", Async: true},
	{ID: "CHAR_DEL_OLD_CHANNELS", SQL: "DELETE FROM channels WHERE ownership = 1 AND lastUsed + ? < UNIX_TIMESTAMP()", Async: true},
	{ID: "CHAR_UPD_EQUIP_SET", SQL: "UPDATE character_equipmentsets SET name=?, iconname=?, ignore_mask=?, item0=?, item1=?, item2=?, item3=?, item4=?, item5=?, item6=?, item7=?, item8=?, item9=?, item10=?, item11=?, item12=?, item13=?, item14=?, item15=?, item16=?, item17=?, item18=? WHERE guid=? AND setguid=? AND setindex=?", Async: true},
	{ID: "CHAR_INS_EQUIP_SET", SQL: "INSERT INTO character_equipmentsets (guid, setguid, setindex, name, iconname, ignore_mask, item0, item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14, item15, item16, item17, item18) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_EQUIP_SET", SQL: "DELETE FROM character_equipmentsets WHERE setguid=?", Async: true},
	{ID: "CHAR_INS_AURA", SQL: "INSERT INTO character_aura (guid, casterGuid, itemGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_ACCOUNT_DATA", SQL: "SELECT type, time, data FROM account_data WHERE accountId = ?", Async: true},
	{ID: "CHAR_REP_ACCOUNT_DATA", SQL: "REPLACE INTO account_data (accountId, type, time, data) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_ACCOUNT_DATA", SQL: "DELETE FROM account_data WHERE accountId = ?", Async: true},
	{ID: "CHAR_SEL_PLAYER_ACCOUNT_DATA", SQL: "SELECT type, time, data FROM character_account_data WHERE guid = ?", Async: true},
	{ID: "CHAR_REP_PLAYER_ACCOUNT_DATA", SQL: "REPLACE INTO character_account_data(guid, type, time, data) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_PLAYER_ACCOUNT_DATA", SQL: "DELETE FROM character_account_data WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_TUTORIALS", SQL: "SELECT tut0, tut1, tut2, tut3, tut4, tut5, tut6, tut7 FROM account_tutorial WHERE accountId = ?", Async: true},
	{ID: "CHAR_INS_TUTORIALS", SQL: "INSERT INTO account_tutorial(tut0, tut1, tut2, tut3, tut4, tut5, tut6, tut7, accountId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_TUTORIALS", SQL: "UPDATE account_tutorial SET tut0 = ?, tut1 = ?, tut2 = ?, tut3 = ?, tut4 = ?, tut5 = ?, tut6 = ?, tut7 = ? WHERE accountId = ?", Async: true},
	{ID: "CHAR_DEL_TUTORIALS", SQL: "DELETE FROM account_tutorial WHERE accountId = ?", Async: true},
	{ID: "CHAR_INS_INSTANCE_SAVE", SQL: "INSERT INTO instance (id, map, resettime, difficulty, completedEncounters, data) VALUES (?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_INSTANCE_DATA", SQL: "UPDATE instance SET completedEncounters=?, data=? WHERE id=?", Async: true},
	{ID: "CHAR_DEL_GAME_EVENT_SAVE", SQL: "DELETE FROM game_event_save WHERE eventEntry = ?", Async: true},
	{ID: "CHAR_INS_GAME_EVENT_SAVE", SQL: "INSERT INTO game_event_save (eventEntry, state, next_start) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_ALL_GAME_EVENT_CONDITION_SAVE", SQL: "DELETE FROM game_event_condition_save WHERE eventEntry = ?", Async: true},
	{ID: "CHAR_DEL_GAME_EVENT_CONDITION_SAVE", SQL: "DELETE FROM game_event_condition_save WHERE eventEntry = ? AND condition_id = ?", Async: true},
	{ID: "CHAR_INS_GAME_EVENT_CONDITION_SAVE", SQL: "INSERT INTO game_event_condition_save (eventEntry, condition_id, done) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_PETITION", SQL: "SELECT ownerguid, name, type FROM petition WHERE petitionguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_SIGNATURE", SQL: "SELECT playerguid FROM petition_sign WHERE petitionguid = ?", Async: false},
	{ID: "CHAR_DEL_ALL_PETITION_SIGNATURES", SQL: "DELETE FROM petition_sign WHERE playerguid = ?", Async: true},
	{ID: "CHAR_DEL_PETITION_SIGNATURE", SQL: "DELETE FROM petition_sign WHERE playerguid = ? AND type = ?", Async: true},
	{ID: "CHAR_SEL_PETITION_BY_OWNER", SQL: "SELECT petitionguid FROM petition WHERE ownerguid = ? AND type = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_TYPE", SQL: "SELECT type FROM petition WHERE petitionguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_SIGNATURES", SQL: "SELECT ownerguid, (SELECT COUNT(playerguid) FROM petition_sign WHERE petition_sign.petitionguid = ?) AS signs, type FROM petition WHERE petitionguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_SIG_BY_ACCOUNT", SQL: "SELECT playerguid FROM petition_sign WHERE player_account = ? AND petitionguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_OWNER_BY_GUID", SQL: "SELECT ownerguid FROM petition WHERE petitionguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_SIG_BY_GUID", SQL: "SELECT ownerguid, petitionguid FROM petition_sign WHERE playerguid = ?", Async: false},
	{ID: "CHAR_SEL_PETITION_SIG_BY_GUID_TYPE", SQL: "SELECT ownerguid, petitionguid FROM petition_sign WHERE playerguid = ? AND type = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_ARENAINFO", SQL: "SELECT arenaTeamId, weekGames, seasonGames, seasonWins, personalRating FROM arena_team_member WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_ARENA_TEAM", SQL: "INSERT INTO arena_team (arenaTeamId, name, captainGuid, type, rating, backgroundColor, emblemStyle, emblemColor, borderStyle, borderColor) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_INS_ARENA_TEAM_MEMBER", SQL: "INSERT INTO arena_team_member (arenaTeamId, guid, personalRating) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_ARENA_TEAM", SQL: "DELETE FROM arena_team where arenaTeamId = ?", Async: true},
	{ID: "CHAR_DEL_ARENA_TEAM_MEMBERS", SQL: "DELETE FROM arena_team_member WHERE arenaTeamId = ?", Async: true},
	{ID: "CHAR_UPD_ARENA_TEAM_CAPTAIN", SQL: "UPDATE arena_team SET captainGuid = ? WHERE arenaTeamId = ?", Async: true},
	{ID: "CHAR_DEL_ARENA_TEAM_MEMBER", SQL: "DELETE FROM arena_team_member WHERE arenaTeamId = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_ARENA_TEAM_STATS", SQL: "UPDATE arena_team SET rating = ?, weekGames = ?, weekWins = ?, seasonGames = ?, seasonWins = ?, `rank` = ? WHERE arenaTeamId = ?", Async: true},
	{ID: "CHAR_UPD_ARENA_TEAM_MEMBER", SQL: "UPDATE arena_team_member SET personalRating = ?, weekGames = ?, weekWins = ?, seasonGames = ?, seasonWins = ? WHERE arenaTeamId = ? AND guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_ARENA_STATS", SQL: "DELETE FROM character_arena_stats WHERE guid = ?", Async: true},
	{ID: "CHAR_REP_CHARACTER_ARENA_STATS", SQL: "REPLACE INTO character_arena_stats (guid, slot, matchMakerRating) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_ARENA_TEAM_NAME", SQL: "UPDATE arena_team SET name = ? WHERE arenaTeamId = ?", Async: true},
	{ID: "CHAR_INS_PLAYER_BGDATA", SQL: "INSERT INTO character_battleground_data (guid, instanceId, team, joinX, joinY, joinZ, joinO, joinMapId, taxiStart, taxiEnd, mountSpell) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_PLAYER_BGDATA", SQL: "DELETE FROM character_battleground_data WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_PLAYER_HOMEBIND", SQL: "INSERT INTO character_homebind (guid, mapId, zoneId, posX, posY, posZ) VALUES (?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_PLAYER_HOMEBIND", SQL: "UPDATE character_homebind SET mapId = ?, zoneId = ?, posX = ?, posY = ?, posZ = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_PLAYER_HOMEBIND", SQL: "DELETE FROM character_homebind WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CORPSES", SQL: "SELECT posX, posY, posZ, orientation, mapId, displayId, itemCache, bytes1, bytes2, guildId, flags, dynFlags, time, corpseType, instanceId, phaseMask, guid FROM corpse WHERE mapId = ? AND instanceId = ?", Async: false},
	{ID: "CHAR_INS_CORPSE", SQL: "INSERT INTO corpse (guid, posX, posY, posZ, orientation, mapId, displayId, itemCache, bytes1, bytes2, guildId, flags, dynFlags, time, corpseType, instanceId, phaseMask) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CORPSE", SQL: "DELETE FROM corpse WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CORPSES_FROM_MAP", SQL: "DELETE FROM corpse WHERE mapId = ? AND instanceId = ?", Async: true},
	{ID: "CHAR_SEL_CORPSE_LOCATION", SQL: "SELECT mapId, posX, posY, posZ, orientation FROM corpse WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_RESPAWNS", SQL: "SELECT type, spawnId, respawnTime FROM respawn WHERE mapId = ? AND instanceId = ?", Async: false},
	{ID: "CHAR_REP_RESPAWN", SQL: "REPLACE INTO respawn (type, spawnId, respawnTime, mapId, instanceId) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_RESPAWN", SQL: "DELETE FROM respawn WHERE type = ? AND spawnId = ? AND mapId = ? AND instanceId = ?", Async: true},
	{ID: "CHAR_DEL_ALL_RESPAWNS", SQL: "DELETE FROM respawn WHERE mapId = ? AND instanceId = ?", Async: true},
	{ID: "CHAR_SEL_GM_TICKETS", SQL: "SELECT id, type, playerGuid, name, description, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, needMoreHelp FROM gm_ticket", Async: false},
	{ID: "CHAR_REP_GM_TICKET", SQL: "REPLACE INTO gm_ticket (id, type, playerGuid, name, description, createTime, mapId, posX, posY, posZ, lastModifiedTime, closedBy, assignedTo, comment, response, completed, escalated, viewed, needMoreHelp, resolvedBy) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GM_TICKET", SQL: "DELETE FROM gm_ticket WHERE id = ?", Async: true},
	{ID: "CHAR_DEL_PLAYER_GM_TICKETS", SQL: "DELETE FROM gm_ticket WHERE playerGuid = ?", Async: true},
	{ID: "CHAR_UPD_PLAYER_GM_TICKETS_ON_CHAR_DELETION", SQL: "UPDATE gm_ticket SET type = 2 WHERE playerGuid = ?", Async: true},
	{ID: "CHAR_INS_GM_SURVEY", SQL: "INSERT INTO gm_survey (guid, surveyId, mainSurvey, comment, createTime) VALUES (?, ?, ?, ?, UNIX_TIMESTAMP(NOW()))", Async: true},
	{ID: "CHAR_INS_GM_SUBSURVEY", SQL: "INSERT INTO gm_subsurvey (surveyId, questionId, answer, answerComment) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_INS_LAG_REPORT", SQL: "INSERT INTO lag_reports (guid, lagType, mapId, posX, posY, posZ, latency, createTime) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_INS_LFG_DATA", SQL: "INSERT INTO lfg_data (guid, dungeon, state) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_LFG_DATA", SQL: "DELETE FROM lfg_data WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHARACTER", SQL: "INSERT INTO characters (guid, account, name, race, class, gender, level, xp, money, skin, face, hairStyle, hairColor, facialStyle, bankSlots, restState, playerFlags, map, instance_id, instance_mode_mask, position_x, position_y, position_z, orientation, trans_x, trans_y, trans_z, trans_o, transguid, taximask, cinematic, totaltime, leveltime, rest_bonus, logout_time, is_logout_resting, resettalents_cost, resettalents_time, extra_flags, stable_slots, at_login, zone, death_expire_time, taxi_path, arenaPoints, totalHonorPoints, todayHonorPoints, yesterdayHonorPoints, totalKills, todayKills, yesterdayKills, chosenTitle, knownCurrencies, watchedFaction, drunk, health, power1, power2, power3, power4, power5, power6, power7, latency, talentGroupsCount, activeTalentGroup, exploredZones, equipmentCache, ammoId, knownTitles, actionBars, grantableLevels) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", Async: true},
	{ID: "CHAR_UPD_CHARACTER", SQL: "UPDATE characters SET name=?,race=?,class=?,gender=?,level=?,xp=?,money=?,skin=?,face=?,hairStyle=?,hairColor=?,facialStyle=?,bankSlots=?,restState=?,playerFlags=?,map=?,instance_id=?,instance_mode_mask=?,position_x=?,position_y=?,position_z=?,orientation=?,trans_x=?,trans_y=?,trans_z=?,trans_o=?,transguid=?,taximask=?,cinematic=?,totaltime=?,leveltime=?,rest_bonus=?,logout_time=?,is_logout_resting=?,resettalents_cost=?,resettalents_time=?,extra_flags=?,stable_slots=?,at_login=?,zone=?,death_expire_time=?,taxi_path=?,arenaPoints=?,totalHonorPoints=?,todayHonorPoints=?,yesterdayHonorPoints=?,totalKills=?,todayKills=?,yesterdayKills=?,chosenTitle=?,knownCurrencies=?,watchedFaction=?,drunk=?,health=?,power1=?,power2=?,power3=?,power4=?,power5=?,power6=?,power7=?,latency=?,talentGroupsCount=?,activeTalentGroup=?,exploredZones=?,equipmentCache=?,ammoId=?,knownTitles=?,actionBars=?,grantableLevels=?,online=? WHERE guid=?", Async: true},
	{ID: "CHAR_UPD_ADD_AT_LOGIN_FLAG", SQL: "UPDATE characters SET at_login = at_login | ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_REM_AT_LOGIN_FLAG", SQL: "UPDATE characters set at_login = at_login & ~ ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_ALL_AT_LOGIN_FLAGS", SQL: "UPDATE characters SET at_login = at_login | ?", Async: true},
	{ID: "CHAR_INS_BUG_REPORT", SQL: "INSERT INTO bugreport (type, content) VALUES(?, ?)", Async: true},
	{ID: "CHAR_UPD_PETITION_NAME", SQL: "UPDATE petition SET name = ? WHERE petitionguid = ?", Async: true},
	{ID: "CHAR_INS_PETITION_SIGNATURE", SQL: "INSERT INTO petition_sign (ownerguid, petitionguid, playerguid, player_account) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_ACCOUNT_ONLINE", SQL: "UPDATE characters SET online = 0 WHERE account = ?", Async: true},
	{ID: "CHAR_INS_GROUP", SQL: "INSERT INTO `groups` (guid, leaderGuid, lootMethod, looterGuid, lootThreshold, icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, groupType, difficulty, raidDifficulty, masterLooterGuid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_INS_GROUP_MEMBER", SQL: "INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GROUP_MEMBER", SQL: "DELETE FROM group_member WHERE memberGuid = ?", Async: true},
	{ID: "CHAR_DEL_GROUP_INSTANCE_PERM_BINDING", SQL: "DELETE FROM group_instance WHERE guid = ? AND instance = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_LEADER", SQL: "UPDATE `groups` SET leaderGuid = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_TYPE", SQL: "UPDATE `groups` SET groupType = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_MEMBER_SUBGROUP", SQL: "UPDATE group_member SET subgroup = ? WHERE memberGuid = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_MEMBER_FLAG", SQL: "UPDATE group_member SET memberFlags = ? WHERE memberGuid = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_DIFFICULTY", SQL: "UPDATE `groups` SET difficulty = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_GROUP_RAID_DIFFICULTY", SQL: "UPDATE `groups` SET raiddifficulty = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_ALL_GM_TICKETS", SQL: "TRUNCATE TABLE gm_ticket", Async: true},
	{ID: "CHAR_DEL_INVALID_SPELL_TALENTS", SQL: "DELETE FROM character_talent WHERE spell = ?", Async: true},
	{ID: "CHAR_DEL_INVALID_SPELL_SPELLS", SQL: "DELETE FROM character_spell WHERE spell = ?", Async: true},
	{ID: "CHAR_UPD_DELETE_INFO", SQL: "UPDATE characters SET deleteInfos_Name = name, deleteInfos_Account = account, deleteDate = UNIX_TIMESTAMP(), name = '', account = 0 WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_RESTORE_DELETE_INFO", SQL: "UPDATE characters SET name = ?, account = ?, deleteDate = NULL, deleteInfos_Name = NULL, deleteInfos_Account = NULL WHERE deleteDate IS NOT NULL AND guid = ?", Async: true},
	{ID: "CHAR_UPD_ZONE", SQL: "UPDATE characters SET zone = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_LEVEL", SQL: "UPDATE characters SET level = ?, xp = 0 WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_INVALID_ACHIEV_PROGRESS_CRITERIA", SQL: "DELETE FROM character_achievement_progress WHERE criteria = ?", Async: true},
	{ID: "CHAR_DEL_INVALID_ACHIEVMENT", SQL: "DELETE FROM character_achievement WHERE achievement = ?", Async: true},
	{ID: "CHAR_INS_ADDON", SQL: "INSERT INTO addons (name, crc) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_INVALID_PET_SPELL", SQL: "DELETE FROM pet_spell WHERE spell = ?", Async: true},
	{ID: "CHAR_DEL_GROUP_INSTANCE_BY_INSTANCE", SQL: "DELETE FROM group_instance WHERE instance = ?", Async: true},
	{ID: "CHAR_DEL_GROUP_INSTANCE_BY_GUID", SQL: "DELETE FROM group_instance WHERE guid = ? AND instance = ?", Async: true},
	{ID: "CHAR_REP_GROUP_INSTANCE", SQL: "REPLACE INTO group_instance (guid, instance, permanent) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_INSTANCE_RESETTIME", SQL: "UPDATE instance SET resettime = ? WHERE id = ?", Async: true},
	{ID: "CHAR_INS_GLOBAL_INSTANCE_RESETTIME", SQL: "INSERT INTO instance_reset (mapid, difficulty, resettime) VALUES (?, ?, ?)", Async: false},
	{ID: "CHAR_DEL_GLOBAL_INSTANCE_RESETTIME", SQL: "DELETE FROM instance_reset WHERE mapid = ? AND difficulty = ?", Async: false},
	{ID: "CHAR_UPD_GLOBAL_INSTANCE_RESETTIME", SQL: "UPDATE instance_reset SET resettime = ? WHERE mapid = ? AND difficulty = ?", Async: false},
	{ID: "CHAR_UPD_CHAR_ONLINE", SQL: "UPDATE characters SET online = 1 WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_NAME_AT_LOGIN", SQL: "UPDATE characters set name = ?, at_login = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_WORLDSTATE", SQL: "UPDATE worldstates SET value = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_INS_WORLDSTATE", SQL: "INSERT INTO worldstates (entry, value) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_INSTANCE_BY_INSTANCE_GUID", SQL: "DELETE FROM character_instance WHERE guid = ? AND instance = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_INSTANCE", SQL: "UPDATE character_instance SET instance = ?, permanent = ?, extendState = ? WHERE guid = ? AND instance = ?", Async: true},
	{ID: "CHAR_INS_CHAR_INSTANCE", SQL: "INSERT INTO character_instance (guid, instance, permanent, extendState) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_GENDER_AND_APPEARANCE", SQL: "UPDATE characters SET gender = ?, skin = ?, face = ?, hairStyle = ?, hairColor = ?, facialStyle = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHARACTER_SKILL", SQL: "DELETE FROM character_skills WHERE guid = ? AND skill = ?", Async: true},
	{ID: "CHAR_UPD_CHARACTER_SOCIAL_FLAGS", SQL: "UPDATE character_social SET flags = ? WHERE guid = ? AND friend = ?", Async: true},
	{ID: "CHAR_INS_CHARACTER_SOCIAL", SQL: "INSERT INTO character_social (guid, friend, flags) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHARACTER_SOCIAL", SQL: "DELETE FROM character_social WHERE guid = ? AND friend = ?", Async: true},
	{ID: "CHAR_UPD_CHARACTER_SOCIAL_NOTE", SQL: "UPDATE character_social SET note = ? WHERE guid = ? AND friend = ?", Async: true},
	{ID: "CHAR_UPD_CHARACTER_POSITION", SQL: "UPDATE characters SET position_x = ?, position_y = ?, position_z = ?, orientation = ?, map = ?, zone = ?, trans_x = 0, trans_y = 0, trans_z = 0, transguid = 0, taxi_path = '', cinematic = 1 WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHARACTER_POSITION_BY_MAPID", SQL: "UPDATE characters SET position_x = ?, position_y = ?, position_z = ?, orientation = ?, map = ?, zone = ?, trans_x = 0, trans_y = 0, trans_z = 0, transguid = 0, taxi_path = '', cinematic = 1 WHERE guid = ? AND map = ?", Async: true},
	{ID: "CHAR_SEL_CHARACTER_AURA_FROZEN", SQL: "SELECT characters.name, character_aura.remainTime FROM characters LEFT JOIN character_aura ON (characters.guid = character_aura.guid) WHERE character_aura.spell = 9454", Async: false},
	{ID: "CHAR_SEL_CHARACTER_ONLINE", SQL: "SELECT name, account, map, zone FROM characters WHERE online > 0", Async: false},
	{ID: "CHAR_SEL_CHAR_DEL_INFO_BY_GUID", SQL: "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL AND guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_DEL_INFO_BY_NAME", SQL: "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL AND deleteInfos_Name LIKE CONCAT('%%', ?, '%%')", Async: false},
	{ID: "CHAR_SEL_CHAR_DEL_INFO", SQL: "SELECT guid, deleteInfos_Name, deleteInfos_Account, deleteDate FROM characters WHERE deleteDate IS NOT NULL", Async: false},
	{ID: "CHAR_SEL_CHARS_BY_ACCOUNT_ID", SQL: "SELECT guid FROM characters WHERE account = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_PINFO", SQL: "SELECT totaltime, level, money, account, race, class, map, zone, gender, health, playerFlags FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_PINFO_BANS", SQL: "SELECT unbandate, bandate = unbandate, bannedby, banreason FROM character_banned WHERE guid = ? AND active ORDER BY bandate ASC LIMIT 1", Async: false},
	{ID: "CHAR_SEL_PINFO_MAILS", SQL: "SELECT SUM(CASE WHEN (checked & 1) THEN 1 ELSE 0 END) AS 'readmail', COUNT(*) AS 'totalmail' FROM mail WHERE `receiver` = ?", Async: false},
	{ID: "CHAR_SEL_PINFO_XP", SQL: "SELECT a.xp, b.guid FROM characters a LEFT JOIN guild_member b ON a.guid = b.guid WHERE a.guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_HOMEBIND", SQL: "SELECT mapId, zoneId, posX, posY, posZ FROM character_homebind WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_GUID_NAME_BY_ACC", SQL: "SELECT guid, name, online FROM characters WHERE account = ?", Async: false},
	{ID: "CHAR_SEL_CHARACTER_AT_LOGIN", SQL: "SELECT at_login FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_CLASS_LVL_AT_LOGIN", SQL: "SELECT class, level, at_login, knownTitles FROM characters WHERE guid = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_CUSTOMIZE_INFO", SQL: "SELECT name, race, class, gender, at_login FROM characters WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_CHAR_RACE_OR_FACTION_CHANGE_INFOS", SQL: "SELECT at_login, knownTitles FROM characters WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_INSTANCE", SQL: "SELECT data, completedEncounters FROM instance WHERE map = ? AND id = ?", Async: false},
	{ID: "CHAR_SEL_PERM_BIND_BY_INSTANCE", SQL: "SELECT guid FROM character_instance WHERE instance = ? and permanent = 1", Async: false},
	{ID: "CHAR_SEL_CHAR_COD_ITEM_MAIL", SQL: "SELECT id, messageType, mailTemplateId, sender, subject, body, money, has_items FROM mail WHERE receiver = ? AND has_items <> 0 AND cod <> 0", Async: false},
	{ID: "CHAR_SEL_CHAR_SOCIAL", SQL: "SELECT DISTINCT guid FROM character_social WHERE friend = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_OLD_CHARS", SQL: "SELECT guid, deleteInfos_Account FROM characters WHERE deleteDate IS NOT NULL AND deleteDate < ?", Async: false},
	{ID: "CHAR_SEL_MAIL", SQL: "SELECT id, messageType, sender, receiver, subject, body, expire_time, deliver_time, money, cod, checked, stationery, mailTemplateId FROM mail WHERE receiver = ? ORDER BY id DESC", Async: true},
	{ID: "CHAR_DEL_CHAR_AURA_FROZEN", SQL: "DELETE FROM character_aura WHERE spell = 9454 AND guid = ?", Async: true},
	{ID: "CHAR_SEL_CHAR_INVENTORY_COUNT_ITEM", SQL: "SELECT COUNT(itemEntry) FROM character_inventory ci INNER JOIN item_instance ii ON ii.guid = ci.item WHERE itemEntry = ?", Async: false},
	{ID: "CHAR_SEL_MAIL_COUNT_ITEM", SQL: "SELECT COUNT(itemEntry) FROM mail_items mi INNER JOIN item_instance ii ON ii.guid = mi.item_guid WHERE itemEntry = ?", Async: false},
	{ID: "CHAR_SEL_AUCTIONHOUSE_COUNT_ITEM", SQL: "SELECT COUNT(itemEntry) FROM auctionhouse ah INNER JOIN item_instance ii ON ii.guid = ah.itemguid WHERE itemEntry = ?", Async: false},
	{ID: "CHAR_SEL_GUILD_BANK_COUNT_ITEM", SQL: "SELECT COUNT(itemEntry) FROM guild_bank_item gbi INNER JOIN item_instance ii ON ii.guid = gbi.item_guid WHERE itemEntry = ?", Async: false},
	{ID: "CHAR_SEL_CHAR_INVENTORY_ITEM_BY_ENTRY", SQL: "SELECT ci.item, cb.slot AS bag, ci.slot, ci.guid, c.account, c.name FROM characters c INNER JOIN character_inventory ci ON ci.guid = c.guid INNER JOIN item_instance ii ON ii.guid = ci.item LEFT JOIN character_inventory cb ON cb.item = ci.bag WHERE ii.itemEntry = ? LIMIT ?", Async: false},
	{ID: "CHAR_SEL_MAIL_ITEMS_BY_ENTRY", SQL: "SELECT mi.item_guid, m.sender, m.receiver, cs.account, cs.name, cr.account, cr.name FROM mail m INNER JOIN mail_items mi ON mi.mail_id = m.id INNER JOIN item_instance ii ON ii.guid = mi.item_guid INNER JOIN characters cs ON cs.guid = m.sender INNER JOIN characters cr ON cr.guid = m.receiver WHERE ii.itemEntry = ? LIMIT ?", Async: false},
	{ID: "CHAR_SEL_AUCTIONHOUSE_ITEM_BY_ENTRY", SQL: "SELECT ah.itemguid, ah.itemowner, c.account, c.name FROM auctionhouse ah INNER JOIN characters c ON c.guid = ah.itemowner INNER JOIN item_instance ii ON ii.guid = ah.itemguid WHERE ii.itemEntry = ? LIMIT ?", Async: false},
	{ID: "CHAR_SEL_GUILD_BANK_ITEM_BY_ENTRY", SQL: "SELECT gi.item_guid, gi.guildid, g.name FROM guild_bank_item gi INNER JOIN guild g ON g.guildid = gi.guildid INNER JOIN item_instance ii ON ii.guid = gi.item_guid WHERE ii.itemEntry = ? LIMIT ?", Async: false},
	{ID: "CHAR_DEL_CHAR_ACHIEVEMENT", SQL: "DELETE FROM character_achievement WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS", SQL: "DELETE FROM character_achievement_progress WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_ACHIEVEMENT", SQL: "INSERT INTO character_achievement (guid, achievement, date) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_ACHIEVEMENT_PROGRESS_BY_CRITERIA", SQL: "DELETE FROM character_achievement_progress WHERE guid = ? AND criteria = ?", Async: true},
	{ID: "CHAR_INS_CHAR_ACHIEVEMENT_PROGRESS", SQL: "INSERT INTO character_achievement_progress (guid, criteria, counter, date) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_REPUTATION_BY_FACTION", SQL: "DELETE FROM character_reputation WHERE guid = ? AND faction = ?", Async: true},
	{ID: "CHAR_INS_CHAR_REPUTATION_BY_FACTION", SQL: "INSERT INTO character_reputation (guid, faction, standing, flags) VALUES (?, ?, ? , ?)", Async: true},
	{ID: "CHAR_UPD_ADD_CHAR_ARENA_POINTS", SQL: "UPDATE characters SET arenaPoints = (arenaPoints + ?) WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_ITEM_REFUND_INSTANCE", SQL: "DELETE FROM item_refund_instance WHERE item_guid = ?", Async: true},
	{ID: "CHAR_INS_ITEM_REFUND_INSTANCE", SQL: "INSERT INTO item_refund_instance (item_guid, player_guid, paidMoney, paidExtendedCost) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_GROUP", SQL: "DELETE FROM `groups` WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_GROUP_MEMBER_ALL", SQL: "DELETE FROM group_member WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_GIFT", SQL: "INSERT INTO character_gifts (guid, item_guid, entry, flags) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_INSTANCE_BY_INSTANCE", SQL: "DELETE FROM instance WHERE id = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_INSTANCE_BY_INSTANCE", SQL: "DELETE FROM character_instance WHERE instance = ?", Async: true},
	{ID: "CHAR_DEL_EXPIRED_CHAR_INSTANCE_BY_MAP_DIFF", SQL: "DELETE FROM character_instance USING character_instance LEFT JOIN instance ON character_instance.instance = id WHERE (extendState = 0 or permanent = 0) and map = ? and difficulty = ?", Async: true},
	{ID: "CHAR_DEL_GROUP_INSTANCE_BY_MAP_DIFF", SQL: "DELETE FROM group_instance USING group_instance LEFT JOIN instance ON group_instance.instance = id WHERE map = ? and difficulty = ?", Async: true},
	{ID: "CHAR_DEL_EXPIRED_INSTANCE_BY_MAP_DIFF", SQL: "DELETE FROM instance WHERE map = ? and difficulty = ? and (SELECT guid FROM character_instance WHERE extendState != 0 AND instance = id LIMIT 1) IS NULL", Async: true},
	{ID: "CHAR_UPD_EXPIRE_CHAR_INSTANCE_BY_MAP_DIFF", SQL: "UPDATE character_instance LEFT JOIN instance ON character_instance.instance = id SET extendState = extendState-1 WHERE map = ? and difficulty = ?", Async: true},
	{ID: "CHAR_DEL_MAIL_ITEM_BY_ID", SQL: "DELETE FROM mail_items WHERE mail_id = ?", Async: true},
	{ID: "CHAR_INS_PETITION", SQL: "INSERT INTO petition (ownerguid, petitionguid, name, type) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_PETITION_BY_GUID", SQL: "DELETE FROM petition WHERE petitionguid = ?", Async: true},
	{ID: "CHAR_DEL_PETITION_SIGNATURE_BY_GUID", SQL: "DELETE FROM petition_sign WHERE petitionguid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_DECLINED_NAME", SQL: "DELETE FROM character_declinedname WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_DECLINED_NAME", SQL: "INSERT INTO character_declinedname (guid, genitive, dative, accusative, instrumental, prepositional) VALUES (?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_CHAR_RACE", SQL: "UPDATE characters SET race = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SKILL_LANGUAGES", SQL: "DELETE FROM character_skills WHERE skill IN (98, 113, 759, 111, 313, 109, 115, 315, 673, 137) AND guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_SKILL_LANGUAGE", SQL: "INSERT INTO `character_skills` (guid, skill, value, max) VALUES (?, ?, 300, 300)", Async: true},
	{ID: "CHAR_UPD_CHAR_TAXI_PATH", SQL: "UPDATE characters SET taxi_path = '' WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_TAXIMASK", SQL: "UPDATE characters SET taximask = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_QUESTSTATUS", SQL: "DELETE FROM character_queststatus WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SOCIAL_BY_GUID", SQL: "DELETE FROM character_social WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SOCIAL_BY_FRIEND", SQL: "DELETE FROM character_social WHERE friend = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_ACHIEVEMENT_BY_ACHIEVEMENT", SQL: "DELETE FROM character_achievement WHERE achievement = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_ACHIEVEMENT", SQL: "UPDATE character_achievement SET achievement = ? where achievement = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_INVENTORY_FACTION_CHANGE", SQL: "UPDATE item_instance ii, character_inventory ci SET ii.itemEntry = ? WHERE ii.itemEntry = ? AND ci.guid = ? AND ci.item = ii.guid", Async: true},
	{ID: "CHAR_DEL_CHAR_SPELL_BY_SPELL", SQL: "DELETE FROM character_spell WHERE spell = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_SPELL_FACTION_CHANGE", SQL: "UPDATE character_spell SET spell = ? where spell = ? AND guid = ?", Async: true},
	{ID: "CHAR_SEL_CHAR_REP_BY_FACTION", SQL: "SELECT standing FROM character_reputation WHERE faction = ? AND guid = ?", Async: false},
	{ID: "CHAR_DEL_CHAR_REP_BY_FACTION", SQL: "DELETE FROM character_reputation WHERE faction = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_REP_FACTION_CHANGE", SQL: "UPDATE character_reputation SET faction = ?, standing = ? WHERE faction = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_TITLES_FACTION_CHANGE", SQL: "UPDATE characters SET knownTitles = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_RES_CHAR_TITLES_FACTION_CHANGE", SQL: "UPDATE characters SET chosenTitle = 0 WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SPELL_COOLDOWNS", SQL: "DELETE FROM character_spell_cooldown WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_SPELL_COOLDOWN", SQL: "INSERT INTO character_spell_cooldown (guid, spell, item, time, categoryId, categoryEnd) VALUES (?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHARACTER", SQL: "DELETE FROM characters WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_ACTION", SQL: "DELETE FROM character_action WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_AURA", SQL: "DELETE FROM character_aura WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_GIFT", SQL: "DELETE FROM character_gifts WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_INSTANCE", SQL: "DELETE FROM character_instance WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_INVENTORY", SQL: "DELETE FROM character_inventory WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_QUESTSTATUS_REWARDED", SQL: "DELETE FROM character_queststatus_rewarded WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_REPUTATION", SQL: "DELETE FROM character_reputation WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SPELL", SQL: "DELETE FROM character_spell WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_MAIL", SQL: "DELETE FROM mail WHERE receiver = ?", Async: true},
	{ID: "CHAR_DEL_MAIL_ITEMS", SQL: "DELETE FROM mail_items WHERE receiver = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_ACHIEVEMENTS", SQL: "DELETE FROM character_achievement WHERE guid = ? AND achievement NOT BETWEEN '456' AND '467' AND achievement NOT BETWEEN '1400' AND '1427' AND achievement NOT IN(1463, 3117, 3259)", Async: true},
	{ID: "CHAR_DEL_CHAR_EQUIPMENTSETS", SQL: "DELETE FROM character_equipmentsets WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_EVENTLOG_BY_PLAYER", SQL: "DELETE FROM guild_eventlog WHERE PlayerGuid1 = ? OR PlayerGuid2 = ?", Async: true},
	{ID: "CHAR_DEL_GUILD_BANK_EVENTLOG_BY_PLAYER", SQL: "DELETE FROM guild_bank_eventlog WHERE PlayerGuid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_GLYPHS", SQL: "DELETE FROM character_glyphs WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_TALENT", SQL: "DELETE FROM character_talent WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SKILLS", SQL: "DELETE FROM character_skills WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_HONOR_POINTS", SQL: "UPDATE characters SET totalHonorPoints = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_ARENA_POINTS", SQL: "UPDATE characters SET arenaPoints = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_MONEY", SQL: "UPDATE characters SET money = ? WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_ACTION", SQL: "INSERT INTO character_action (guid, spec, button, action, type) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_CHAR_ACTION", SQL: "UPDATE character_action SET action = ?, type = ? WHERE guid = ? AND button = ? AND spec = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_ACTION_BY_BUTTON_SPEC", SQL: "DELETE FROM character_action WHERE guid = ? and button = ? and spec = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_INVENTORY_BY_ITEM", SQL: "DELETE FROM character_inventory WHERE item = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_INVENTORY_BY_BAG_SLOT", SQL: "DELETE FROM character_inventory WHERE bag = ? AND slot = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_MAIL", SQL: "UPDATE mail SET has_items = ?, expire_time = ?, deliver_time = ?, money = ?, cod = ?, checked = ? WHERE id = ?", Async: true},
	{ID: "CHAR_REP_CHAR_QUESTSTATUS", SQL: "REPLACE INTO character_queststatus (guid, quest, status, explored, timer, mobcount1, mobcount2, mobcount3, mobcount4, itemcount1, itemcount2, itemcount3, itemcount4, itemcount5, itemcount6, playercount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_QUESTSTATUS_BY_QUEST", SQL: "DELETE FROM character_queststatus WHERE guid = ? AND quest = ?", Async: true},
	{ID: "CHAR_INS_CHAR_QUESTSTATUS_REWARDED", SQL: "INSERT IGNORE INTO character_queststatus_rewarded (guid, quest, active) VALUES (?, ?, 1)", Async: true},
	{ID: "CHAR_DEL_CHAR_QUESTSTATUS_REWARDED_BY_QUEST", SQL: "DELETE FROM character_queststatus_rewarded WHERE guid = ? AND quest = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_QUESTSTATUS_REWARDED_FACTION_CHANGE", SQL: "UPDATE character_queststatus_rewarded SET quest = ? WHERE quest = ? AND guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_QUESTSTATUS_REWARDED_ACTIVE", SQL: "UPDATE character_queststatus_rewarded SET active = 1 WHERE guid = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_QUESTSTATUS_REWARDED_ACTIVE_BY_QUEST", SQL: "UPDATE character_queststatus_rewarded SET active = 0 WHERE quest = ? AND guid = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_SKILL_BY_SKILL", SQL: "DELETE FROM character_skills WHERE guid = ? AND skill = ?", Async: true},
	{ID: "CHAR_INS_CHAR_SKILLS", SQL: "INSERT INTO character_skills (guid, skill, value, max) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_CHAR_SKILLS", SQL: "UPDATE character_skills SET value = ?, max = ? WHERE guid = ? AND skill = ?", Async: true},
	{ID: "CHAR_INS_CHAR_SPELL", SQL: "INSERT INTO character_spell (guid, spell, active, disabled) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_STATS", SQL: "DELETE FROM character_stats WHERE guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_STATS", SQL: "INSERT INTO character_stats (guid, maxhealth, maxpower1, maxpower2, maxpower3, maxpower4, maxpower5, maxpower6, maxpower7, strength, agility, stamina, intellect, spirit, armor, resHoly, resFire, resNature, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, rangedCritPct, spellCritPct, attackPower, rangedAttackPower, spellPower, resilience) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_PETITION_BY_OWNER", SQL: "DELETE FROM petition WHERE ownerguid = ?", Async: true},
	{ID: "CHAR_DEL_PETITION_SIGNATURE_BY_OWNER", SQL: "DELETE FROM petition_sign WHERE ownerguid = ?", Async: true},
	{ID: "CHAR_DEL_PETITION_BY_OWNER_AND_TYPE", SQL: "DELETE FROM petition WHERE ownerguid = ? AND type = ?", Async: true},
	{ID: "CHAR_DEL_PETITION_SIGNATURE_BY_OWNER_AND_TYPE", SQL: "DELETE FROM petition_sign WHERE ownerguid = ? AND type = ?", Async: true},
	{ID: "CHAR_INS_CHAR_GLYPHS", SQL: "INSERT INTO character_glyphs VALUES(?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_TALENT_BY_SPELL_SPEC", SQL: "DELETE FROM character_talent WHERE guid = ? AND spell = ? AND talentGroup = ?", Async: true},
	{ID: "CHAR_INS_CHAR_TALENT", SQL: "INSERT INTO character_talent (guid, spell, talentGroup) VALUES (?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_ACTION_EXCEPT_SPEC", SQL: "DELETE FROM character_action WHERE spec<>? AND guid = ?", Async: true},
	{ID: "CHAR_INS_CHAR_FISHINGSTEPS", SQL: "INSERT INTO character_fishingsteps (guid, fishingSteps) VALUES (?, ?)", Async: true},
	{ID: "CHAR_DEL_CHAR_FISHINGSTEPS", SQL: "DELETE FROM character_fishingsteps WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_ITEMCONTAINER_ITEMS", SQL: "SELECT container_id, item_id, item_count, follow_rules, ffa, blocked, counted, under_threshold, needs_quest, rnd_prop, rnd_suffix FROM item_loot_items", Async: false},
	{ID: "CHAR_DEL_ITEMCONTAINER_ITEMS", SQL: "DELETE FROM item_loot_items WHERE container_id = ?", Async: true},
	{ID: "CHAR_DEL_ITEMCONTAINER_ITEM", SQL: "DELETE FROM item_loot_items WHERE container_id = ? AND item_id = ? AND item_count = ?", Async: true},
	{ID: "CHAR_INS_ITEMCONTAINER_ITEMS", SQL: "INSERT INTO item_loot_items (container_id, item_id, item_count, follow_rules, ffa, blocked, counted, under_threshold, needs_quest, rnd_prop, rnd_suffix) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_ITEMCONTAINER_MONEY", SQL: "SELECT container_id, money FROM item_loot_money", Async: false},
	{ID: "CHAR_DEL_ITEMCONTAINER_MONEY", SQL: "DELETE FROM item_loot_money WHERE container_id = ?", Async: true},
	{ID: "CHAR_INS_ITEMCONTAINER_MONEY", SQL: "INSERT INTO item_loot_money (container_id, money) VALUES (?, ?)", Async: true},
	{ID: "CHAR_REP_CALENDAR_EVENT", SQL: "REPLACE INTO calendar_events (id, creator, title, description, type, dungeon, eventtime, flags, time2) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CALENDAR_EVENT", SQL: "DELETE FROM calendar_events WHERE id = ?", Async: true},
	{ID: "CHAR_REP_CALENDAR_INVITE", SQL: "REPLACE INTO calendar_invites (id, event, invitee, sender, status, statustime, `rank`, text) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_DEL_CALENDAR_INVITE", SQL: "DELETE FROM calendar_invites WHERE id = ?", Async: true},
	{ID: "CHAR_SEL_CHAR_PET_IDS", SQL: "SELECT id FROM character_pet WHERE owner = ?", Async: false},
	{ID: "CHAR_DEL_CHAR_PET_DECLINEDNAME_BY_OWNER", SQL: "DELETE FROM character_pet_declinedname WHERE owner = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_PET_DECLINEDNAME", SQL: "DELETE FROM character_pet_declinedname WHERE id = ?", Async: true},
	{ID: "CHAR_INS_CHAR_PET_DECLINEDNAME", SQL: "INSERT INTO character_pet_declinedname (id, owner, genitive, dative, accusative, instrumental, prepositional) VALUES (?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_PET_AURA", SQL: "SELECT casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience FROM pet_aura WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_PET_SPELL", SQL: "SELECT spell, active FROM pet_spell WHERE guid = ?", Async: true},
	{ID: "CHAR_SEL_PET_SPELL_COOLDOWN", SQL: "SELECT spell, time, categoryId, categoryEnd FROM pet_spell_cooldown WHERE guid = ? AND time > UNIX_TIMESTAMP()", Async: true},
	{ID: "CHAR_SEL_PET_DECLINED_NAME", SQL: "SELECT genitive, dative, accusative, instrumental, prepositional FROM character_pet_declinedname WHERE owner = ? AND id = ?", Async: true},
	{ID: "CHAR_DEL_PET_AURAS", SQL: "DELETE FROM pet_aura WHERE guid = ?", Async: false},
	{ID: "CHAR_DEL_PET_SPELLS", SQL: "DELETE FROM pet_spell WHERE guid = ?", Async: true},
	{ID: "CHAR_DEL_PET_SPELL_COOLDOWNS", SQL: "DELETE FROM pet_spell_cooldown WHERE guid = ?", Async: false},
	{ID: "CHAR_INS_PET_SPELL_COOLDOWN", SQL: "INSERT INTO pet_spell_cooldown (guid, spell, time, categoryId, categoryEnd) VALUES (?, ?, ?, ?, ?)", Async: false},
	{ID: "CHAR_DEL_PET_SPELL_BY_SPELL", SQL: "DELETE FROM pet_spell WHERE guid = ? and spell = ?", Async: true},
	{ID: "CHAR_INS_PET_SPELL", SQL: "INSERT INTO pet_spell (guid, spell, active) VALUES (?, ?, ?)", Async: false},
	{ID: "CHAR_INS_PET_AURA", SQL: "INSERT INTO pet_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: false},
	{ID: "CHAR_SEL_CHAR_PETS", SQL: "SELECT id, entry, modelid, level, exp, Reactstate, slot, name, renamed, curhealth, curmana, curhappiness, abdata, savetime, CreatedBySpell, PetType FROM character_pet WHERE owner = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_PET_BY_OWNER", SQL: "DELETE FROM character_pet WHERE owner = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_PET_NAME", SQL: "UPDATE character_pet SET name = ?, renamed = 1 WHERE owner = ? AND id = ?", Async: true},
	{ID: "CHAR_UPD_CHAR_PET_SLOT_BY_ID", SQL: "UPDATE character_pet SET slot = ? WHERE owner = ? AND id = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_PET_BY_ID", SQL: "DELETE FROM character_pet WHERE id = ?", Async: true},
	{ID: "CHAR_DEL_CHAR_PET_BY_SLOT", SQL: "DELETE FROM character_pet WHERE owner = ? AND (slot = ? OR slot > ?)", Async: true},
	{ID: "CHAR_INS_PET", SQL: "INSERT INTO character_pet (id, entry, owner, modelid, level, exp, Reactstate, slot, name, renamed, curhealth, curmana, curhappiness, abdata, savetime, CreatedBySpell, PetType) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_PVPSTATS_MAXID", SQL: "SELECT MAX(id) FROM pvpstats_battlegrounds", Async: false},
	{ID: "CHAR_INS_PVPSTATS_BATTLEGROUND", SQL: "INSERT INTO pvpstats_battlegrounds (id, winner_faction, bracket_id, type, date) VALUES (?, ?, ?, ?, NOW())", Async: true},
	{ID: "CHAR_INS_PVPSTATS_PLAYER", SQL: "INSERT INTO pvpstats_players (battleground_id, character_guid, winner, score_killing_blows, score_deaths, score_honorable_kills, score_bonus_honor, score_damage_done, score_healing_done, attr_1, attr_2, attr_3, attr_4, attr_5) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "CHAR_SEL_PVPSTATS_FACTIONS_OVERALL", SQL: "SELECT winner_faction, COUNT(*) AS count FROM pvpstats_battlegrounds WHERE DATEDIFF(NOW(), date) < 7 GROUP BY winner_faction ORDER BY winner_faction ASC", Async: false},
	{ID: "CHAR_INS_QUEST_TRACK", SQL: "INSERT INTO quest_tracker (id, character_guid, quest_accept_time, core_hash, core_revision) VALUES (?, ?, NOW(), ?, ?)", Async: true},
	{ID: "CHAR_UPD_QUEST_TRACK_GM_COMPLETE", SQL: "UPDATE quest_tracker SET completed_by_gm = 1 WHERE id = ? AND character_guid = ? ORDER BY quest_accept_time DESC LIMIT 1", Async: true},
	{ID: "CHAR_UPD_QUEST_TRACK_COMPLETE_TIME", SQL: "UPDATE quest_tracker SET quest_complete_time = NOW() WHERE id = ? AND character_guid = ? ORDER BY quest_accept_time DESC LIMIT 1", Async: true},
	{ID: "CHAR_UPD_QUEST_TRACK_ABANDON_TIME", SQL: "UPDATE quest_tracker SET quest_abandon_time = NOW() WHERE id = ? AND character_guid = ? ORDER BY quest_accept_time DESC LIMIT 1", Async: true},
	{ID: "CHAR_INS_DESERTER_TRACK", SQL: "INSERT INTO battleground_deserters (guid, type, datetime) VALUES (?, ?, NOW())", Async: true},
	{ID: "CHAR_UPD_NPCBOT_OWNER", SQL: "UPDATE characters_npcbot SET owner = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_UPD_NPCBOT_OWNER_ALL", SQL: "UPDATE characters_npcbot SET owner = ? WHERE owner = ?", Async: true},
	{ID: "CHAR_UPD_NPCBOT_ROLES", SQL: "UPDATE characters_npcbot SET roles = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_SEL_NPCBOT_EQUIP_BY_ITEM_INSTANCE", SQL: "SELECT creatorGuid, giftCreatorGuid, count, duration, charges, flags, enchantments, randomPropertyId, durability, playedTime, text, guid, itemEntry, owner_guid FROM item_instance WHERE guid IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: false},
	{ID: "CHAR_UPD_NPCBOT_EQUIP", SQL: "UPDATE characters_npcbot SET equipMhEx = ?, equipOhEx = ?, equipRhEx = ?, equipHead = ?, equipShoulders = ?, equipChest = ?, equipWaist = ?, equipLegs = ?, equipFeet = ?, equipWrist = ?, equipHands = ?, equipBack = ?, equipBody = ?, equipFinger1 = ?, equipFinger2 = ?, equipTrinket1 = ?, equipTrinket2 = ?, equipNeck = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_DEL_NPCBOT", SQL: "DELETE FROM characters_npcbot WHERE entry = ?", Async: true},
	{ID: "CHAR_INS_NPCBOT", SQL: "INSERT INTO characters_npcbot (entry, roles, spec, faction) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "CHAR_UPD_NPCBOT_FACTION", SQL: "UPDATE characters_npcbot SET faction = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_UPD_NPCBOT_SPEC", SQL: "UPDATE characters_npcbot SET spec = ? WHERE entry = ?", Async: true},
	{ID: "CHAR_UPD_NPCBOT_DISABLED_SPELLS", SQL: "UPDATE characters_npcbot SET spells_disabled = ? WHERE entry = ?", Async: true},
}

var WorldStatements = []StatementDefinition{
	{ID: "WORLD_DEL_LINKED_RESPAWN", SQL: "DELETE FROM linked_respawn WHERE guid = ? AND linkType  = ?", Async: true},
	{ID: "WORLD_DEL_LINKED_RESPAWN_MASTER", SQL: "DELETE FROM linked_respawn WHERE linkedGuid = ? AND linkType = ?", Async: true},
	{ID: "WORLD_REP_LINKED_RESPAWN", SQL: "REPLACE INTO linked_respawn (guid, linkedGuid, linkType) VALUES (?, ?, ?)", Async: true},
	{ID: "WORLD_SEL_CREATURE_TEXT", SQL: "SELECT CreatureID, GroupID, ID, Text, Type, Language, Probability, Emote, Duration, Sound, BroadcastTextId, TextRange FROM creature_text", Async: false},
	{ID: "WORLD_SEL_SMART_SCRIPTS", SQL: "SELECT entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o FROM smart_scripts ORDER BY entryorguid, source_type, id, link", Async: false},
	{ID: "WORLD_SEL_SMARTAI_WP", SQL: "SELECT entry, pointid, position_x, position_y, position_z, orientation, delay FROM waypoints ORDER BY entry, pointid", Async: false},
	{ID: "WORLD_DEL_GAMEOBJECT", SQL: "DELETE FROM gameobject WHERE guid = ?", Async: true},
	{ID: "WORLD_DEL_EVENT_GAMEOBJECT", SQL: "DELETE FROM game_event_gameobject WHERE guid = ?", Async: true},
	{ID: "WORLD_INS_GRAVEYARD_ZONE", SQL: "INSERT INTO graveyard_zone (ID, GhostZone, Faction) VALUES (?, ?, ?)", Async: true},
	{ID: "WORLD_DEL_GRAVEYARD_ZONE", SQL: "DELETE FROM graveyard_zone WHERE ID = ? AND GhostZone = ? AND Faction = ?", Async: true},
	{ID: "WORLD_INS_GAME_TELE", SQL: "INSERT INTO game_tele (id, position_x, position_y, position_z, orientation, map, name) VALUES (?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_DEL_GAME_TELE", SQL: "DELETE FROM game_tele WHERE name = ?", Async: true},
	{ID: "WORLD_INS_NPC_VENDOR", SQL: "INSERT INTO npc_vendor (entry, item, maxcount, incrtime, extendedcost) VALUES(?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_DEL_NPC_VENDOR", SQL: "DELETE FROM npc_vendor WHERE entry = ? AND item = ?", Async: true},
	{ID: "WORLD_SEL_NPC_VENDOR_REF", SQL: "SELECT item, maxcount, incrtime, ExtendedCost FROM npc_vendor WHERE entry = ? ORDER BY slot ASC", Async: false},
	{ID: "WORLD_UPD_CREATURE_MOVEMENT_TYPE", SQL: "UPDATE creature SET MovementType = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_FACTION", SQL: "UPDATE creature_template SET faction = ? WHERE entry = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_NPCFLAG", SQL: "UPDATE creature_template SET npcflag = ? WHERE entry = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_POSITION", SQL: "UPDATE creature SET position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_WANDER_DISTANCE", SQL: "UPDATE creature SET wander_distance = ?, MovementType = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_SPAWN_TIME_SECS", SQL: "UPDATE creature SET spawntimesecs = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_INS_CREATURE_FORMATION", SQL: "INSERT INTO creature_formations (leaderGUID, memberGUID, dist, angle, groupAI) VALUES (?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_INS_WAYPOINT_DATA", SQL: "INSERT INTO waypoint_data (id, point, position_x, position_y, position_z, orientation) VALUES (?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_DEL_WAYPOINT_DATA", SQL: "DELETE FROM waypoint_data WHERE id = ? AND point = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_DATA_POINT", SQL: "UPDATE waypoint_data SET point = point - 1 WHERE id = ? AND point > ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_DATA_POSITION", SQL: "UPDATE waypoint_data SET position_x = ?, position_y = ?, position_z = ?, orientation = ? where id = ? AND point = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_DATA_WPGUID", SQL: "UPDATE waypoint_data SET wpguid = ? WHERE id = ? and point = ?", Async: true},
	{ID: "WORLD_SEL_WAYPOINT_DATA_MAX_ID", SQL: "SELECT MAX(id) FROM waypoint_data", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_MAX_POINT", SQL: "SELECT MAX(point) FROM waypoint_data WHERE id = ?", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_BY_ID", SQL: "SELECT point, position_x, position_y, position_z, orientation, move_type, delay, action, action_chance FROM waypoint_data WHERE id = ? ORDER BY point", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_POS_BY_ID", SQL: "SELECT point, position_x, position_y, position_z, orientation FROM waypoint_data WHERE id = ?", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_POS_FIRST_BY_ID", SQL: "SELECT position_x, position_y, position_z, orientation FROM waypoint_data WHERE point = 1 AND id = ?", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_POS_LAST_BY_ID", SQL: "SELECT position_x, position_y, position_z, orientation FROM waypoint_data WHERE id = ? ORDER BY point DESC LIMIT 1", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_BY_WPGUID", SQL: "SELECT id, point FROM waypoint_data WHERE wpguid = ?", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_ALL_BY_WPGUID", SQL: "SELECT id, point, delay, move_type, action, action_chance FROM waypoint_data WHERE wpguid = ?", Async: false},
	{ID: "WORLD_UPD_WAYPOINT_DATA_ALL_WPGUID", SQL: "UPDATE waypoint_data SET wpguid = 0", Async: true},
	{ID: "WORLD_SEL_WAYPOINT_DATA_BY_POS", SQL: "SELECT id, point FROM waypoint_data WHERE (abs(position_x - ?) <= ?) and (abs(position_y - ?) <= ?) and (abs(position_z - ?) <= ?)", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_WPGUID_BY_ID", SQL: "SELECT wpguid FROM waypoint_data WHERE id = ? and wpguid <> 0", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_DATA_ACTION", SQL: "SELECT DISTINCT action FROM waypoint_data", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_SCRIPTS_MAX_ID", SQL: "SELECT MAX(guid) FROM waypoint_scripts", Async: false},
	{ID: "WORLD_INS_CREATURE_ADDON", SQL: "INSERT INTO creature_addon(guid, path_id) VALUES (?, ?)", Async: true},
	{ID: "WORLD_UPD_CREATURE_ADDON_PATH", SQL: "UPDATE creature_addon SET path_id = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_DEL_CREATURE_ADDON", SQL: "DELETE FROM creature_addon WHERE guid = ?", Async: true},
	{ID: "WORLD_SEL_CREATURE_ADDON_BY_GUID", SQL: "SELECT guid FROM creature_addon WHERE guid = ?", Async: false},
	{ID: "WORLD_INS_WAYPOINT_SCRIPT", SQL: "INSERT INTO waypoint_scripts (guid) VALUES (?)", Async: true},
	{ID: "WORLD_DEL_WAYPOINT_SCRIPT", SQL: "DELETE FROM waypoint_scripts WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_SCRIPT_ID", SQL: "UPDATE waypoint_scripts SET id = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_SCRIPT_X", SQL: "UPDATE waypoint_scripts SET x = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_SCRIPT_Y", SQL: "UPDATE waypoint_scripts SET y = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_SCRIPT_Z", SQL: "UPDATE waypoint_scripts SET z = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_WAYPOINT_SCRIPT_O", SQL: "UPDATE waypoint_scripts SET o = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_SEL_WAYPOINT_SCRIPT_ID_BY_GUID", SQL: "SELECT id FROM waypoint_scripts WHERE guid = ?", Async: false},
	{ID: "WORLD_DEL_CREATURE", SQL: "DELETE FROM creature WHERE guid = ?", Async: true},
	{ID: "WORLD_SEL_COMMANDS", SQL: "SELECT name, help FROM command", Async: false},
	{ID: "WORLD_SEL_CREATURE_TEMPLATE", SQL: "SELECT entry, difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, modelid1, modelid2, modelid3, modelid4, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, scale, `rank`, dmgschool, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance, unit_class, unit_flags, unit_flags2, dynamicflags, family, type, type_flags, lootid, pickpocketloot, skinloot, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType, ctm.Ground, ctm.Swim, ctm.Flight, ctm.Rooted, ctm.Chase, ctm.Random, HoverHeight, HealthModifier, ManaModifier, ArmorModifier, DamageModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth, mechanic_immune_mask, spell_school_immune_mask, flags_extra, ScriptName FROM creature_template ct LEFT JOIN creature_template_movement ctm ON ct.entry = ctm.CreatureId WHERE entry = ?", Async: false},
	{ID: "WORLD_SEL_WAYPOINT_SCRIPT_BY_ID", SQL: "SELECT guid, delay, command, datalong, datalong2, dataint, x, y, z, o FROM waypoint_scripts WHERE id = ?", Async: false},
	{ID: "WORLD_SEL_ITEM_TEMPLATE_BY_NAME", SQL: "SELECT entry FROM item_template WHERE name = ?", Async: false},
	{ID: "WORLD_SEL_CREATURE_BY_ID", SQL: "SELECT guid FROM creature WHERE id = ?", Async: false},
	{ID: "WORLD_SEL_GAMEOBJECT_NEAREST", SQL: "SELECT guid, id, position_x, position_y, position_z, map, (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) AS order_ FROM gameobject WHERE map = ? AND (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) <= ? ORDER BY order_", Async: false},
	{ID: "WORLD_SEL_CREATURE_NEAREST", SQL: "SELECT guid, id, position_x, position_y, position_z, map, (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) AS order_ FROM creature WHERE map = ? AND (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) <= ? ORDER BY order_", Async: false},
	{ID: "WORLD_INS_CREATURE", SQL: "INSERT INTO creature (guid, id , map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, wander_distance, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_DEL_GAME_EVENT_CREATURE", SQL: "DELETE FROM game_event_creature WHERE guid = ?", Async: true},
	{ID: "WORLD_DEL_GAME_EVENT_MODEL_EQUIP", SQL: "DELETE FROM game_event_model_equip WHERE guid = ?", Async: true},
	{ID: "WORLD_INS_GAMEOBJECT", SQL: "INSERT INTO gameobject (guid, id, map, spawnMask, phaseMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", Async: true},
	{ID: "WORLD_INS_DISABLES", SQL: "INSERT INTO disables (entry, sourceType, flags, comment) VALUES (?, ?, ?, ?)", Async: true},
	{ID: "WORLD_SEL_DISABLES", SQL: "SELECT entry FROM disables WHERE entry = ? AND sourceType = ?", Async: false},
	{ID: "WORLD_DEL_DISABLES", SQL: "DELETE FROM disables WHERE entry = ? AND sourceType = ?", Async: true},
	{ID: "WORLD_UPD_CREATURE_ZONE_AREA_DATA", SQL: "UPDATE creature SET zoneId = ?, areaId = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_UPD_GAMEOBJECT_ZONE_AREA_DATA", SQL: "UPDATE gameobject SET zoneId = ?, areaId = ? WHERE guid = ?", Async: true},
	{ID: "WORLD_DEL_SPAWNGROUP_MEMBER", SQL: "DELETE FROM spawn_group WHERE spawnType = ? AND spawnId = ?", Async: true},
	{ID: "WORLD_DEL_GAMEOBJECT_ADDON", SQL: "DELETE FROM gameobject_addon WHERE guid = ?", Async: true},
}

func AllStatements() []StatementDefinition {
	result := make([]StatementDefinition, 0, 612)
	result = append(result, LoginStatements...)
	result = append(result, CharacterStatements...)
	result = append(result, WorldStatements...)
	return result
}
